-- Physical final table contract: [SupplyChain_Gold_Warehouse].[ForecastAccuracy_DW].[DimCustomerGrouping]
-- Loaded by ETL_Framework from [SupplyChain_Gold_Warehouse].[ForecastAccuracy_DW_Wrk].[v_DimCustomerGrouping].
-- Business/source view SQL is documented in ../ForecastAccuracy_DW_Wrk/v_DimCustomerGrouping.sql.
