#!/usr/bin/env python3
from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
OUT = ROOT / "03_operations" / "orchestration"

REF_TABLES = [
    "Calendar",
    "CustomerAccount",
    "CustomerAccountGroup",
    "CustomerGrouping",
    "CustomerShippingLocation",
    "ForecastCycle",
    "ForecastHorizon",
    "ItemMaster",
    "OrderType",
    "Vendor",
    "Warehouse",
]


@dataclass(frozen=True)
class ProcSpec:
    rel_path: str
    database: str
    procedure: str
    targets: list[tuple[str, str]]
    mart: str
    wave_note: str


def exec_block(database: str, schema: str, table: str) -> str:
    return (
        "    EXEC [ETL_Framework].[DW_Developer].[usp_RefreshCuratedTableFromView]\n"
        f"        '{database}', '{schema}', '{table}';"
    )


def render(spec: ProcSpec) -> str:
    blocks = "\n\n".join(exec_block(spec.database, schema, table) for schema, table in spec.targets)
    return f"""-- Target database: {spec.database}
-- Mart: {spec.mart}
-- Wave order: {spec.wave_note}
-- Generated by 03_operations/tools/generate_wave_sps.py
CREATE OR ALTER PROCEDURE [dbo].[{spec.procedure}]
AS
BEGIN
    SET NOCOUNT ON;

{blocks}
END;
"""


def specs() -> list[ProcSpec]:
    return [
        ProcSpec(
            rel_path="shared/sql/SupplyChain_Processing_Warehouse.dbo.Usp_Refresh_Shared_ReferenceMaster.sql",
            database="SupplyChain_Processing_Warehouse",
            procedure="Usp_Refresh_Shared_ReferenceMaster",
            targets=[("ReferenceMaster_Enh", name) for name in REF_TABLES],
            mart="shared",
            wave_note="Shared W01 ReferenceMaster prerequisites",
        ),
        ProcSpec(
            rel_path="shared/sql/SupplyChain_Processing_Warehouse.dbo.Usp_Refresh_Shared_Staging.sql",
            database="SupplyChain_Processing_Warehouse",
            procedure="Usp_Refresh_Shared_Staging",
            targets=[("Staging", "DemandForecastSnapshotDaily")],
            mart="shared",
            wave_note="Shared W01 Staging prerequisites",
        ),
        ProcSpec(
            rel_path="forecast_accuracy/sql/SupplyChain_Processing_Warehouse.dbo.Usp_Refresh_ForecastAccuracy_Silver_W01.sql",
            database="SupplyChain_Processing_Warehouse",
            procedure="Usp_Refresh_ForecastAccuracy_Silver_W01",
            targets=[
                ("SalesHistory_Enh", "InvoiceDetailLineLevel"),
                ("OpenOrderHistory_Enh", "OpenOrderLineLevel"),
            ],
            mart="forecast_accuracy",
            wave_note="Silver W01 line-level tables",
        ),
        ProcSpec(
            rel_path="forecast_accuracy/sql/SupplyChain_Processing_Warehouse.dbo.Usp_Refresh_ForecastAccuracy_Silver_W02.sql",
            database="SupplyChain_Processing_Warehouse",
            procedure="Usp_Refresh_ForecastAccuracy_Silver_W02",
            targets=[
                ("SalesHistory_Enh", "ActualDemandMonthly"),
                ("SalesHistory_Enh", "ActualDemandWeekly"),
                ("SalesHistory_Enh", "InvoiceWeekly"),
                ("ForecastHistory_Enh", "ForecastDemandMonthly"),
                ("OpenOrderHistory_Enh", "OpenOrderMonthly"),
            ],
            mart="forecast_accuracy",
            wave_note="Silver W02 aggregate tables",
        ),
        ProcSpec(
            rel_path="forecast_accuracy/sql/SupplyChain_Processing_Warehouse.dbo.Usp_Refresh_ForecastAccuracy_Silver_W03.sql",
            database="SupplyChain_Processing_Warehouse",
            procedure="Usp_Refresh_ForecastAccuracy_Silver_W03",
            targets=[("ForecastHistory_Enh", "NaiveForecastMonthly")],
            mart="forecast_accuracy",
            wave_note="Silver W03 derived forecast table",
        ),
        ProcSpec(
            rel_path="inventory_health/sql/SupplyChain_Processing_Warehouse.dbo.Usp_Refresh_InventoryHealth_Silver_W01.sql",
            database="SupplyChain_Processing_Warehouse",
            procedure="Usp_Refresh_InventoryHealth_Silver_W01",
            targets=[
                ("InventoryHistory_Enh", "InventorySnapshotWeekly"),
                ("InventoryHistory_Enh", "AtpWeekEnding"),
            ],
            mart="inventory_health",
            wave_note="Silver W01 inventory source transformations",
        ),
        ProcSpec(
            rel_path="inventory_health/sql/SupplyChain_Processing_Warehouse.dbo.Usp_Refresh_InventoryHealth_Silver_W02.sql",
            database="SupplyChain_Processing_Warehouse",
            procedure="Usp_Refresh_InventoryHealth_Silver_W02",
            targets=[
                ("InventoryHistory_Enh", "PurchaseOrderSnapshotHistorical"),
                ("InventoryHistory_Enh", "ManufacturingOrderSnapshotDaily"),
                ("InventoryHistory_Enh", "HoldingTransferSnapshotDaily"),
                ("InventoryHistory_Enh", "ForecastSnapshotWeekly"),
                ("InventoryHistory_Enh", "SupplyPlanDetail"),
                ("InventoryHistory_Enh", "ItemBalanceHistorical_WithInTransit"),
                ("InventoryHistory_Enh", "SafetyStockHelper"),
                ("SalesHistory_Enh", "InvoiceDetailLineLevel"),
            ],
            mart="inventory_health",
            wave_note="Silver W02 derived source tables",
        ),
        ProcSpec(
            rel_path="inventory_health/sql/SupplyChain_Processing_Warehouse.dbo.Usp_Refresh_InventoryHealth_Silver_W03.sql",
            database="SupplyChain_Processing_Warehouse",
            procedure="Usp_Refresh_InventoryHealth_Silver_W03",
            targets=[
                ("InventoryHistory_Enh", "AFIStatusSnapshotWeekly"),
                ("InventoryHistory_Enh", "AwdHelper"),
                ("InventoryHistory_Enh", "LastInvoiceWeekly"),
                ("InventoryHistory_Enh", "Cogs52WWeekly"),
            ],
            mart="inventory_health",
            wave_note="Silver W03 dependent helper tables",
        ),
    ]


def main() -> int:
    for spec in specs():
        path = OUT / spec.rel_path
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(render(spec), encoding="utf-8")
        print(path.relative_to(ROOT))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
