CREATE VIEW ForecastAccuracy_DW.v_DimProduct AS
-- ===========================================================================
-- v_DimProduct — Backward-compatible view for v9 semantic model TMDL
-- Generated 2026-05-20 — fix Delta protocol violation after EDW Exit swap
--
-- Source: SupplyChain_Processing_Warehouse.ReferenceMaster_Enh.ItemMaster (174 cols)
-- Target: 89 cols expected by sc_forecast_control_tower semantic model TMDL
--
-- Categories:
--   §A — 17 cols  matched EXACTLY (passthrough)
--   §B — 42 cols  RENAMED (v9 suffix removed in EL → alias back)
--   §C — 30 cols  TRULY MISSING in EL (NULL stub — visual will show blank)
--   §D — 118 cols  BONUS (extra EL cols not in TMDL — exposed for future use)
--
-- VERIFIED 2026-05-20: scan all TMDL files showed 0 DAX measures / 0 relationships
--   reference the missing cols → NULL stub safe.
-- ===========================================================================
SELECT
-- §A. Direct match (17 cols)
    RTRIM([ItemSKU]) AS [ItemSKU],
    [Item],
    [SeriesName],
    [ItemClassCode],
    [ItemClassName],
    [ItemCode],
    [ItemStyleCode],
    [RetailCategoryCode],
    [RetailCategoryName],
    [AssociationCode],
    [SalesClassCode],
    [AFISalesCategoryCode],
    [AFISalesDivisionCode],
    [DiscountClassCode],
    [CommissionClassCode],
    [FreightClassCode],
    [ImportDomesticCode],

-- §B. Renamed aliases (42 cols) — v9 name kept for TMDL compat
    [ItemDescription] AS [ItemDescriptionName],
    [QtyInBox] AS [QtyInBoxNum],
    [UOM] AS [UOMCode],
    [SeriesColor] AS [SeriesColorName],
    [SeriesDescription] AS [SeriesDescriptionName],
    [SHSeriesDescription] AS [ShSeriesDescriptionName],
    [ItemClassName] AS [ItemClassFullName],
    [ItemGrouping] AS [ItemGroupingName],
    [ItemStyleGroup] AS [ItemStyleGroupName],
    [ItemStyle] AS [ItemStyleName],
    [ProductLine] AS [ProductLineName],
    [MerchandisingCategory] AS [MerchandisingCategoryName],
    [PricePoint] AS [PricePointName],
    [SalesClassDescription] AS [SalesClassDescriptionName],
    [SalesClass] AS [SalesClassName],
    [AFISalesCategory] AS [AFISalesCategoryName],
    [AFISalesDivision] AS [AFISalesDivisionName],
    [AFIFinanceDivision] AS [AFIFinanceDivisionName],
    [DiscountClassDescription] AS [DiscountClassDescriptionName],
    [DiscountClass] AS [DiscountClassName],
    [CommissionClassDescription] AS [CommissionClassDescriptionName],
    [CommissionClass] AS [CommissionClassName],
    [FreightClassDescription] AS [FreightClassDescriptionName],
    [FreightClass] AS [FreightClassName],
    [CollectiveClass] AS [CollectiveClassCode],
    [CollectiveClass] AS [CollectiveClassName],
    [ResponsibleOffice] AS [ResponsibleOfficeCode],
    [CountryofOrigin] AS [CountryOfOriginName],
    [AFIItemStatus] AS [AFIItemStatusCode],
    [ManufacturingStatus] AS [ManufacturingStatusCode],
    [MarketingItemStatus] AS [MarketingItemStatusCode],
    [ManufacturingStatusChangeDate] AS [ManufacturingStatusChange],
    [CommodityItem] AS [CommodityItemNum],
    [BenchcraftProductFlag] AS [IsBenchcraftProduct],
    [NewMillenniumProductFlag] AS [IsNewMillenniumProduct],
    [ShanghaiStore] AS [IsShanghaiStore],
    [DefaultGroup] AS [DefaultGroupNum],
    [MarketIntroducedAt] AS [MarketIntroducedAtName],
    [PrimaryVendor] AS [PrimaryVendorCode],
    [PrimaryVendor] AS [PrimaryVendorName],
    [InitialInvoicePeriod] AS [InitialInvoicePeriodCode],
    [ItemForecastPlannerID] AS [ItemForecastPlanner],

-- §C. NULL stubs (30 cols) — v9-only cols not in EL schema
    CAST(NULL AS VARCHAR(50)) AS [SKProduct],
    CAST(NULL AS VARCHAR(50)) AS [SCPItem],
    CAST(NULL AS VARCHAR(100)) AS [ColorName],
    CAST(NULL AS VARCHAR(50)) AS [SeriesCode],
    CAST(NULL AS VARCHAR(50)) AS [ExtSeriesCode],
    CAST(NULL AS VARCHAR(50)) AS [ItemExtSeriesCode],
    CAST(NULL AS VARCHAR(200)) AS [ItemDescSeriesName],
    CAST(NULL AS VARCHAR(200)) AS [ShItemDescSeriesName],
    CAST(NULL AS VARCHAR(200)) AS [ItemDescSeriesColorName],
    CAST(NULL AS VARCHAR(100)) AS [ChildStyleName],
    CAST(NULL AS VARCHAR(100)) AS [ParentStyleName],
    CAST(NULL AS VARCHAR(50)) AS [CexCode],
    CAST(NULL AS VARCHAR(20)) AS [CurrentSCPManufacturingStatusCode],
    CAST(NULL AS VARCHAR(100)) AS [MarketingStatusName],
    CAST(NULL AS VARCHAR(20)) AS [CurrentStatusCode],
    CAST(NULL AS BIT) AS [IsMainPiece],
    CAST(NULL AS VARCHAR(20)) AS [SellableItemCode],
    CAST(NULL AS BIT) AS [IsF123Product],
    CAST(NULL AS BIT) AS [IsHsCoreProduct],
    CAST(NULL AS BIT) AS [IsHsProprietaryProduct],
    CAST(NULL AS BIT) AS [IsHsExclusive],
    CAST(NULL AS BIT) AS [IsBerklineProduct],
    CAST(NULL AS BIT) AS [IsBardiniProduct],
    CAST(NULL AS DATE) AS [MarketBegin],
    CAST(NULL AS DATE) AS [MarketEnd],
    CAST(NULL AS DECIMAL(18,4)) AS [AmtFobPrice],
    CAST(NULL AS VARCHAR(20)) AS [GoodBetterBestCode],
    CAST(NULL AS INT) AS [GbbSortNum],
    CAST(NULL AS DECIMAL(18,4)) AS [QtyInitialInvoice],
    CAST(NULL AS VARCHAR(50)) AS [MainPieceCode],

-- §D. Bonus EL cols (118 cols) — extra columns from EL not exposed in v9 TMDL
    [AFIFinanceDivisionCode],
    [BardiniProductFlag],
    [BerklineProductFlag],
    [CEXCode] AS [CEXCodeSource],
    [CartonDepthInches],
    [CartonDepthMeters],
    [CartonHeightInches],
    [CartonHeightMeters],
    [CartonWidthInches],
    [CartonWidthMeters],
    [ChildStyleDescription],
    [Colors],
    [CommonCarrierFlag],
    [ConsumerChoiceFlag],
    [Cubes],
    [CurrentUnitCost],
    [DiningSeriesFlag],
    [DiscontinuedDate],
    [DiscontinuedFlag],
    [DiscontinuedYearPeriod],
    [Division],
    [DivisionRanking],
    [ERetailChannelSku],
    [ERetailSeriesName],
    [ERetailSeriesNumber],
    [EligibleForProtectionPlan],
    [ExclusiveComment],
    [ExpressShipFlag],
    [ExtSeriesNumber],
    [F123ProductFlag],
    [FOBArcPrice],
    [FluffAFI],
    [FrameNumber],
    [FriendlyDimensions],
    [GBBSortId],
    [GoodBetterBestForPricePoint],
    [GroupPriceIncr],
    [GroupPricePointType],
    [HSCoreProductFlag],
    [HSExclusiveFlag],
    [HSProprietaryProductFlag],
    [InitialInvoiceQty],
    [IsProtectionPlan],
    [ItemAmazonBrandOwner],
    [ItemBedSizeType],
    [ItemBedStyleType],
    [ItemClass],
    [ItemConsumerDescription],
    [ItemDescriptionSeries],
    [ItemDescriptionSeriesItemColor],
    [ItemEcomMerchantNotes],
    [ItemGeneralColor],
    [ItemHomeStoreProductLine],
    [ItemImage],
    [ItemIsRTA],
    [ItemKey],
    [ItemMerchGridOverridePhoto],
    [ItemName],
    [ItemPricePointRating],
    [ItemSupplierDirectShipOnly],
    [ItemTableShapeType],
    [ItemThirdPartyItem],
    [ItemType],
    [KeyItem],
    [Knockout],
    [Lifestyle],
    [LoadDT],
    [MainPieceItem],
    [MarketBeginDate],
    [MarketEndDate],
    [MarketingStatusDescription],
    [MasterGroupCode],
    [Material],
    [MfgWarranty],
    [NewItemFlag],
    [ParentStyleDescription],
    [PowerMotionSeriesFlag],
    [PreviousStatusCode],
    [PrimaryChannelSku],
    [PrimarySeriesName],
    [PrimarySeriesNumber],
    [ProductDepthInches],
    [ProductDepthMeters],
    [ProductHeightInches],
    [ProductHeightMeters],
    [ProductWidthInches],
    [ProductWidthMeters],
    [ReclinerSeriesFlag],
    [ResponsibleOfficeName],
    [RetailBrandName],
    [RetailCategoryChargeType],
    [RetailCategoryDescription],
    [RetailCategoryGroup],
    [RetailDepartmentName],
    [RetailTypeDescription],
    [RowID],
    [SHItemDescriptionSeries],
    [Scene7ImageSet],
    [Seats],
    [SellableItemFlag],
    [SeriesDateArchived],
    [SeriesDiscontinuedFlag],
    [SeriesFeatures],
    [SeriesGrouping],
    [SeriesImage],
    [SeriesMainImage],
    [SeriesNumber],
    [SeriesPrimary],
    [SeriesThirdParty],
    [Showroom],
    [SofaTableSeriesFlag],
    [StandAloneFlag],
    [StatusCodeChangeDate],
    [SuppWeightNetWeightLbs],
    [TrendArrow],
    [UPC],
    [UnitWeightLbs],
    [WedgeSeriesFlag]
FROM SupplyChain_Processing_Warehouse.ReferenceMaster_Enh.ItemMaster;
