CREATE VIEW Shared_DW.v_DimProduct AS
-- ===========================================================================
-- Shared_DW.v_DimProduct — canonical shared item/product dimension
-- Generated 2026-05-29 from Forecast DimProduct compatibility contract +
-- Inventory Health item attributes. One physical key/column spelling: ItemSKU.
-- Source of record: Enterprise_Lakehouse.MasterData_DW.DimItemMaster.
-- ===========================================================================
SELECT
-- §A. Direct match (17 cols)
    RTRIM(d.[ItemSKU]) AS [ItemSKU],
    d.[Item],
    d.[SeriesName],
    d.[ItemClassCode],
    d.[ItemClassName],
    d.[ItemCode],
    d.[ItemStyleCode],
    d.[RetailCategoryCode],
    d.[RetailCategoryName],
    d.[AssociationCode],
    d.[SalesClassCode],
    d.[AFISalesCategoryCode],
    d.[AFISalesDivisionCode],
    d.[DiscountClassCode],
    d.[CommissionClassCode],
    d.[FreightClassCode],
    d.[ImportDomesticCode],

-- §B. Renamed aliases (42 cols) — v9 name kept for TMDL compat
    d.[ItemDescription] AS [ItemDescriptionName],
    d.[QtyInBox] AS [QtyInBoxNum],
    d.[UOM] AS [UOMCode],
    d.[SeriesColor] AS [SeriesColorName],
    d.[SeriesDescription] AS [SeriesDescriptionName],
    d.[SHSeriesDescription] AS [ShSeriesDescriptionName],
    d.[ItemClassName] AS [ItemClassFullName],
    d.[ItemGrouping] AS [ItemGroupingName],
    d.[ItemStyleGroup] AS [ItemStyleGroupName],
    d.[ItemStyle] AS [ItemStyleName],
    d.[ProductLine] AS [ProductLineName],
    d.[MerchandisingCategory] AS [MerchandisingCategoryName],
    d.[PricePoint] AS [PricePointName],
    d.[SalesClassDescription] AS [SalesClassDescriptionName],
    d.[SalesClass] AS [SalesClassName],
    d.[AFISalesCategory] AS [AFISalesCategoryName],
    d.[AFISalesDivision] AS [AFISalesDivisionName],
    d.[AFIFinanceDivision] AS [AFIFinanceDivisionName],
    d.[DiscountClassDescription] AS [DiscountClassDescriptionName],
    d.[DiscountClass] AS [DiscountClassName],
    d.[CommissionClassDescription] AS [CommissionClassDescriptionName],
    d.[CommissionClass] AS [CommissionClassName],
    d.[FreightClassDescription] AS [FreightClassDescriptionName],
    d.[FreightClass] AS [FreightClassName],
    d.[CollectiveClass] AS [CollectiveClassCode],
    d.[CollectiveClass] AS [CollectiveClassName],
    d.[ResponsibleOffice] AS [ResponsibleOfficeCode],
    d.[CountryofOrigin] AS [CountryOfOriginName],
    d.[AFIItemStatus] AS [AFIItemStatusCode],
    d.[ManufacturingStatus] AS [ManufacturingStatusCode],
    d.[MarketingItemStatus] AS [MarketingItemStatusCode],
    d.[ManufacturingStatusChangeDate] AS [ManufacturingStatusChange],
    d.[CommodityItem] AS [CommodityItemNum],
    d.[BenchcraftProductFlag] AS [IsBenchcraftProduct],
    d.[NewMillenniumProductFlag] AS [IsNewMillenniumProduct],
    d.[ShanghaiStore] AS [IsShanghaiStore],
    d.[DefaultGroup] AS [DefaultGroupNum],
    d.[MarketIntroducedAt] AS [MarketIntroducedAtName],
    d.[PrimaryVendor] AS [PrimaryVendorCode],
    d.[PrimaryVendor] AS [PrimaryVendorName],
    d.[InitialInvoicePeriod] AS [InitialInvoicePeriodCode],
    d.[ItemForecastPlannerID] AS [ItemForecastPlanner],

-- §C. NULL stubs (30 cols) — v9-only cols not in EL schema
    CAST(NULL AS VARCHAR(50)) AS [SKProduct],
    CAST(NULL AS VARCHAR(50)) AS [SCPItem],
    CAST(NULL AS VARCHAR(100)) AS [ColorName],
    CAST(NULL AS VARCHAR(50)) AS [SeriesCode],
    CAST(NULL AS VARCHAR(50)) AS [ExtSeriesCode],
    CAST(NULL AS VARCHAR(50)) AS [ItemExtSeriesCode],
    CAST(NULL AS VARCHAR(200)) AS [ItemDescSeriesName],
    CAST(NULL AS VARCHAR(200)) AS [ShItemDescSeriesName],
    CAST(NULL AS VARCHAR(200)) AS [ItemDescSeriesColorName],
    CAST(NULL AS VARCHAR(100)) AS [ChildStyleName],
    CAST(NULL AS VARCHAR(100)) AS [ParentStyleName],
    CAST(NULL AS VARCHAR(50)) AS [CexCode],
    CAST(NULL AS VARCHAR(20)) AS [CurrentSCPManufacturingStatusCode],
    CAST(NULL AS VARCHAR(100)) AS [MarketingStatusName],
    CAST(NULL AS VARCHAR(20)) AS [CurrentStatusCode],
    CAST(NULL AS BIT) AS [IsMainPiece],
    CAST(NULL AS VARCHAR(20)) AS [SellableItemCode],
    CAST(NULL AS BIT) AS [IsF123Product],
    CAST(NULL AS BIT) AS [IsHsCoreProduct],
    CAST(NULL AS BIT) AS [IsHsProprietaryProduct],
    CAST(NULL AS BIT) AS [IsHsExclusive],
    CAST(NULL AS BIT) AS [IsBerklineProduct],
    CAST(NULL AS BIT) AS [IsBardiniProduct],
    CAST(NULL AS DATE) AS [MarketBegin],
    CAST(NULL AS DATE) AS [MarketEnd],
    CAST(NULL AS DECIMAL(18,4)) AS [AmtFobPrice],
    CAST(NULL AS VARCHAR(20)) AS [GoodBetterBestCode],
    CAST(NULL AS INT) AS [GbbSortNum],
    CAST(NULL AS DECIMAL(18,4)) AS [QtyInitialInvoice],
    CAST(NULL AS VARCHAR(50)) AS [MainPieceCode],

-- §D. Bonus EL cols (118 cols) — extra columns from EL not exposed in v9 TMDL
    d.[AFIFinanceDivisionCode],
    d.[BardiniProductFlag],
    d.[BerklineProductFlag],
    d.[CEXCode] AS [CEXCodeSource],
    d.[CartonDepthInches],
    d.[CartonDepthMeters],
    d.[CartonHeightInches],
    d.[CartonHeightMeters],
    d.[CartonWidthInches],
    d.[CartonWidthMeters],
    d.[ChildStyleDescription],
    d.[Colors],
    d.[CommonCarrierFlag],
    d.[ConsumerChoiceFlag],
    d.[Cubes],
    d.[CurrentUnitCost],
    d.[DiningSeriesFlag],
    d.[DiscontinuedDate],
    d.[DiscontinuedFlag],
    d.[DiscontinuedYearPeriod],
    d.[Division],
    d.[DivisionRanking],
    d.[ERetailChannelSku],
    d.[ERetailSeriesName],
    d.[ERetailSeriesNumber],
    d.[EligibleForProtectionPlan],
    d.[ExclusiveComment],
    d.[ExpressShipFlag],
    d.[ExtSeriesNumber],
    d.[F123ProductFlag],
    d.[FOBArcPrice],
    d.[FluffAFI],
    d.[FrameNumber],
    d.[FriendlyDimensions],
    d.[GBBSortId],
    d.[GoodBetterBestForPricePoint],
    d.[GroupPriceIncr],
    d.[GroupPricePointType],
    d.[HSCoreProductFlag],
    d.[HSExclusiveFlag],
    d.[HSProprietaryProductFlag],
    d.[InitialInvoiceQty],
    d.[IsProtectionPlan],
    d.[ItemAmazonBrandOwner],
    d.[ItemBedSizeType],
    d.[ItemBedStyleType],
    d.[ItemClass],
    d.[ItemConsumerDescription],
    d.[ItemDescriptionSeries],
    d.[ItemDescriptionSeriesItemColor],
    d.[ItemEcomMerchantNotes],
    d.[ItemGeneralColor],
    d.[ItemHomeStoreProductLine],
    d.[ItemImage],
    d.[ItemIsRTA],
    d.[ItemKey],
    d.[ItemMerchGridOverridePhoto],
    d.[ItemName],
    d.[ItemPricePointRating],
    d.[ItemSupplierDirectShipOnly],
    d.[ItemTableShapeType],
    d.[ItemThirdPartyItem],
    d.[ItemType],
    d.[KeyItem],
    d.[Knockout],
    d.[Lifestyle],
    CAST(GETUTCDATE() AS DATETIME2(6)) AS [LoadDT],
    d.[MainPieceItem],
    d.[MarketBeginDate],
    d.[MarketEndDate],
    d.[MarketingStatusDescription],
    d.[MasterGroupCode],
    d.[Material],
    d.[MfgWarranty],
    d.[NewItemFlag],
    d.[ParentStyleDescription],
    d.[PowerMotionSeriesFlag],
    d.[PreviousStatusCode],
    d.[PrimaryChannelSku],
    d.[PrimarySeriesName],
    d.[PrimarySeriesNumber],
    d.[ProductDepthInches],
    d.[ProductDepthMeters],
    d.[ProductHeightInches],
    d.[ProductHeightMeters],
    d.[ProductWidthInches],
    d.[ProductWidthMeters],
    d.[ReclinerSeriesFlag],
    d.[ResponsibleOfficeName],
    d.[RetailBrandName],
    d.[RetailCategoryChargeType],
    d.[RetailCategoryDescription],
    d.[RetailCategoryGroup],
    d.[RetailDepartmentName],
    d.[RetailTypeDescription],
    d.[RowID],
    d.[SHItemDescriptionSeries],
    d.[Scene7ImageSet],
    d.[Seats],
    d.[SellableItemFlag],
    d.[SeriesDateArchived],
    d.[SeriesDiscontinuedFlag],
    d.[SeriesFeatures],
    d.[SeriesGrouping],
    d.[SeriesImage],
    d.[SeriesMainImage],
    d.[SeriesNumber],
    d.[SeriesPrimary],
    d.[SeriesThirdParty],
    d.[Showroom],
    d.[SofaTableSeriesFlag],
    d.[StandAloneFlag],
    d.[StatusCodeChangeDate],
    d.[SuppWeightNetWeightLbs],
    d.[TrendArrow],
    d.[UPC],
    d.[UnitWeightLbs],
    d.[WedgeSeriesFlag],
    CAST(d.[ItemDescription] AS VARCHAR(200)) AS [ItemDescription],
    CAST(d.[RetailCategoryName] AS VARCHAR(100)) AS [CategoryName],
    CAST(d.[RetailCategoryCode] AS VARCHAR(50)) AS [CategoryCode],
    CAST(d.[CollectiveClass] AS VARCHAR(50)) AS [CollectiveClass],
    CAST(d.[SeriesDescription] AS VARCHAR(200)) AS [SeriesDescription],
    CAST(TRIM(d.[AFIItemStatus]) AS VARCHAR(10)) AS [AfiItemStatus],
    CAST(CASE
        WHEN d.[DiscontinuedFlag] = 1 THEN 'Discontinued'
        WHEN TRIM(d.[AFIItemStatus]) = 'N' THEN 'New'
        WHEN TRIM(d.[AFIItemStatus]) = 'A' THEN 'Active'
        WHEN TRIM(d.[AFIItemStatus]) IN ('D','R') THEN 'Inactive'
        ELSE 'Other'
    END AS VARCHAR(20)) AS [LifecycleStatus],
    CAST(TRIM(d.[PrimaryVendor]) AS VARCHAR(50)) AS [PrimaryVendorNumber],
    CAST(v.[VendorName] AS VARCHAR(200)) AS [PrimaryVendorDisplayName],
    CAST(CASE
        WHEN LEFT(TRIM(d.[ItemClassCode]),1) = 'Z' AND RIGHT(TRIM(d.[ItemClassCode]),1) = 'K'
        THEN 1 ELSE 0 END AS BIT) AS [IsFinishedGoodsItem],
    CAST(ISNULL(u.[UnavailableFlag], 0) AS BIT) AS [UnavailableFlag]
FROM [Enterprise_Lakehouse].[MasterData_DW].[DimItemMaster] d
LEFT JOIN [Enterprise_Lakehouse].[Purchasing_AFI].[VendorMaster] v
       ON TRIM(v.[VendorNumber]) = TRIM(d.[PrimaryVendor])
LEFT JOIN (
    SELECT TRIM([ITNBR]) AS [ItemSKU],
           MAX(CASE WHEN TRIM([MFPUS]) = 'U' THEN 1 ELSE 0 END) AS [UnavailableFlag]
    FROM [Enterprise_Lakehouse].[ItemMaster_AFI].[ITBEXT]
    WHERE [ITNBR] IS NOT NULL AND TRIM([ITNBR]) <> ''
    GROUP BY TRIM([ITNBR])
) u ON u.[ItemSKU] = TRIM(d.[ItemSKU])
WHERE d.[ItemSKU] IS NOT NULL AND TRIM(d.[ItemSKU]) <> ''
