-- Target database: SupplyChain_Processing_Warehouse
-- Mart: forecast_accuracy
-- Wave order: Silver W02 aggregate tables
-- Generated by 03_operations/tools/generate_wave_sps.py
CREATE   PROCEDURE [dbo].[Usp_Refresh_ForecastAccuracy_Silver_W02]
AS
BEGIN
    SET NOCOUNT ON;

    DECLARE @ForecastWindowStart date = DATEADD(day, -90, CAST(GETDATE() AS date));

    IF NOT EXISTS
    (
        SELECT TOP (1) 1
        FROM [ForecastHistory_Enh_Wrk].[v_ForecastDemandMonthly]
        WHERE Snapshot >= @ForecastWindowStart
    )
    BEGIN
        THROW 51010,
            'ForecastDemandMonthly DateRange guard failed: target was not changed because the source 90-day window is empty.',
            1;
    END;

    EXEC [ETL_Framework].[DW_Developer].[usp_RefreshCuratedTableFromView]
        'SupplyChain_Processing_Warehouse', 'SalesHistory_Enh', 'ActualDemandMonthly';

    EXEC [ETL_Framework].[DW_Developer].[usp_RefreshCuratedTableFromView]
        'SupplyChain_Processing_Warehouse', 'SalesHistory_Enh', 'ActualDemandWeekly';

    EXEC [ETL_Framework].[DW_Developer].[usp_RefreshCuratedTableFromView]
        'SupplyChain_Processing_Warehouse', 'SalesHistory_Enh', 'InvoiceWeekly';

    EXEC [ETL_Framework].[DW_Developer].[usp_UpdateCuratedTableFromView_DateRange]
        'SupplyChain_Processing_Warehouse', 'ForecastHistory_Enh', 'ForecastDemandMonthly', 'Snapshot', 'Snapshot', -90;

    EXEC [ETL_Framework].[DW_Developer].[usp_RefreshCuratedTableFromView]
        'SupplyChain_Processing_Warehouse', 'OpenOrderHistory_Enh', 'OpenOrderMonthly';
END;

GO
