-- Generated from live Fabric metadata: SupplyChain_Processing_Warehouse
CREATE TABLE [SalesHistory_Enh].[InvoiceDetailLineLevel] (
    [InvoiceID] decimal(9,0) NOT NULL,
    [InvoiceExtended] varchar(8000) NULL,
    [OrderID] varchar(8000) NOT NULL,
    [ItemSequenceNum] decimal(7,0) NULL,
    [Customer] varchar(8000) NOT NULL,
    [ShipToCode] varchar(8000) NOT NULL,
    [AccountShipTo] varchar(8000) NULL,
    [ItemSKU] varchar(8000) NOT NULL,
    [WarehouseCode] varchar(8000) NOT NULL,
    [CustomerGroupCode] varchar(8000) NULL,
    [LeadTimeDaysNum] int NULL,
    [QtyShipped] decimal(7,0) NOT NULL,
    [QtyOrdered] decimal(7,0) NOT NULL,
    [QtyBackordered] decimal(7,0) NOT NULL,
    [AmtInvoice] decimal(9,2) NOT NULL,
    [AmtNetSales] decimal(13,3) NULL,
    [AmtPrice] decimal(9,2) NOT NULL,
    [AmtStandardPrice] decimal(7,2) NULL,
    [AmtContractPrice] decimal(7,2) NULL,
    [AmtDiscount] decimal(9,2) NOT NULL,
    [AmtPriceAdjustment] decimal(9,2) NOT NULL,
    [AmtFreight] decimal(9,2) NOT NULL,
    [InvoiceDate] date NULL,
    [OrderDate] date NULL,
    [Request] date NULL,
    [CurrentRequest] date NULL,
    [CurrentPromise] date NULL,
    [OriginalRequest] date NULL,
    [OriginalPromise] date NULL,
    [PromisedDelivery] date NULL,
    [Delivery] date NULL,
    [ActualDelivery] date NULL,
    [OrderTypeCode] varchar(8000) NULL,
    [OrderType3Code] varchar(8000) NULL,
    [CreditCode] varchar(8000) NOT NULL,
    [ItemClassCode] varchar(8000) NOT NULL,
    [OrderItemStatusCode] varchar(8000) NULL,
    [LoadDT] datetime2(6) NULL
);
