-- Generated from live Fabric metadata: Enterprise_Lakehouse
CREATE TABLE [SalesHistory_AFI].[InvoiceDetail] (
    [CustomerNumber] varchar(8000) NOT NULL,
    [InvoiceNumber] decimal(9,0) NOT NULL,
    [ItemSKU] varchar(8000) NOT NULL,
    [ItemSequence] decimal(7,0) NULL,
    [QuantityShipped] decimal(7,0) NOT NULL,
    [InvoiceAmount] decimal(9,2) NOT NULL,
    [OrderNumber] varchar(8000) NOT NULL,
    [ShiptoNumber] varchar(8000) NOT NULL,
    [QuantityOrdered] decimal(7,0) NOT NULL,
    [QuantityBackOrdered] decimal(7,0) NOT NULL,
    [CreditCode] varchar(8000) NOT NULL,
    [Warehouse] varchar(8000) NOT NULL,
    [BilltoSalesman] varchar(8000) NOT NULL,
    [ShiptoSalesman] varchar(8000) NOT NULL,
    [Discount] decimal(9,2) NOT NULL,
    [PriceAdjustment] decimal(9,2) NOT NULL,
    [PostingMonth] varchar(8000) NOT NULL,
    [Freight] decimal(9,2) NOT NULL,
    [Price] decimal(9,2) NOT NULL,
    [ItemClass] varchar(8000) NOT NULL,
    [ExtendedInvoiceNumber] varchar(8000) NULL,
    [PurchaseOrder] varchar(8000) NOT NULL,
    [RequestDate] date NULL,
    [InvoiceDate] date NULL,
    [DefaultDeliveryDays] varchar(8000) NULL,
    [TripNumber] decimal(7,0) NULL,
    [DropNumber] decimal(2,0) NULL,
    [PromisedDelivery] date NULL,
    [OrderEntry] date NULL,
    [PriorityCode] decimal(2,0) NULL,
    [OrderItemStatus] varchar(8000) NULL,
    [OrderPriority] decimal(2,0) NULL,
    [OriginalRequestDate] date NULL,
    [ActualDelivery] date NULL,
    [CustomerSku] varchar(8000) NULL,
    [LineReleaseNumber] varchar(8000) NULL,
    [NetSales] decimal(13,3) NULL,
    [StandardPrice] decimal(7,2) NULL,
    [AdvertisingAccrual] decimal(9,2) NULL,
    [DFIDiscount] decimal(9,2) NULL,
    [ContractPrice] decimal(7,2) NULL,
    [CurrencyCode] varchar(8000) NULL,
    [DeliveryDays] int NULL,
    [DeliveryDaysOriginalPromiseDate] int NULL,
    [DeliveryDaysRaw] int NULL,
    [DeliveryDaysOriginalPromiseDateRaw] int NULL,
    [OriginalInvoiceNumber] decimal(8,0) NULL,
    [OriginalInvoiceDate] date NULL,
    [OriginalOrderNumber] varchar(8000) NULL,
    [OriginalOrderDate] date NULL,
    [OriginalSequenceNumber] decimal(7,0) NULL,
    [OriginalDeliveryMethod] varchar(8000) NULL,
    [OrderType] varchar(8000) NULL,
    [OrderDate] date NULL,
    [OriginalPromiseDate] date NULL,
    [CurrentRequestDate] date NULL,
    [DeliveryDate] date NULL,
    [TripCloseDate] date NULL,
    [FirstScanDate] date NULL,
    [TripCreateDate] date NULL,
    [CurrentPromiseDate] date NULL,
    [PriceCode] varchar(8000) NULL,
    [ItemDiscountCode] varchar(8000) NULL,
    [commissioncode] varchar(8000) NULL,
    [FreightCode] varchar(8000) NULL,
    [DiscountSalesClass] varchar(8000) NULL,
    [ExceptionID] decimal(7,0) NULL,
    [FreightSalesClass] varchar(8000) NULL,
    [BuyGroupCode] varchar(8000) NULL,
    [GroupPricingExceptionID] decimal(10,0) NULL,
    [WarehouseOperationPercent] decimal(6,0) NULL,
    [PriceAdderPercent] decimal(6,0) NULL,
    [CalculatedAllowancePercent] decimal(7,0) NULL,
    [PackageDiscountAllocationPercent] decimal(4,0) NULL,
    [PackageDescription] varchar(8000) NULL,
    [PackageID] varchar(8000) NULL,
    [PackagePrice] decimal(8,0) NULL,
    [PackageItemPrice] decimal(8,0) NULL,
    [PackageItemDiscount] decimal(4,0) NULL,
    [OrderType3] varchar(8000) NULL
);
