-- Generated from live Fabric metadata: SupplyChain_Gold_Warehouse
CREATE TABLE [InventoryHealth_DW].[FactInventoryHealthSnapshot] (
    [ItemSku] varchar(50) NULL,
    [WarehouseCode] varchar(50) NULL,
    [SnapshotWeekEndingDate] date NULL,
    [OnHandQty] decimal(18,4) NULL,
    [OnHand Value] decimal(18,4) NULL,
    [On Order Qty] decimal(18,4) NULL,
    [POOnOrderQty] decimal(18,4) NULL,
    [MOOnOrderQty] decimal(18,4) NULL,
    [In Transit Qty] decimal(18,4) NULL,
    [TransferInInTransitQty] decimal(18,4) NULL,
    [POInTransitQty] decimal(18,4) NULL,
    [On Order Value] decimal(18,4) NULL,
    [In Transit Value] decimal(18,4) NULL,
    [AwdQty] decimal(18,4) NULL,
    [On Hold Ratio] decimal(18,4) NULL,
    [IsActiveItemWhIn7DNext] int NULL,
    [IsActiveItemWhIn14DNext] int NULL,
    [ATP Qty] decimal(18,4) NULL,
    [SIQty] decimal(18,4) NULL,
    [Revenue at risk] decimal(18,4) NULL,
    [InventoryClassification Final Status] varchar(30) NULL,
    [Qty by InventoryClassification (InActive)] decimal(18,4) NULL,
    [Qty by InventoryClassification (SLOB)] decimal(18,4) NULL,
    [Qty by InventoryClassification (Below Target)] decimal(18,4) NULL,
    [Qty by InventoryClassification (SweetSpot)] decimal(18,4) NULL,
    [Qty by InventoryClassification (OverTarget)] decimal(18,4) NULL,
    [Qty by InventoryClassification (Excess)] decimal(18,4) NULL,
    [Qty by InventoryClassification (AE)] decimal(18,4) NULL,
    [Qty by InventoryClassification (TB Inventory)] decimal(18,4) NULL,
    [SafetyStockTarget] decimal(18,4) NULL,
    [FirmDemandQtyAtRisk] decimal(18,4) NULL,
    [NetFcstQtyAtRisk] decimal(18,4) NULL,
    [FirmDemandQty] decimal(18,4) NULL,
    [NetFcstQty] decimal(18,4) NULL,
    [COGS52W] decimal(18,4) NULL,
    [IsShortage/Surplus/InStock] varchar(30) NULL,
    [Shortage/Surplus Qty] decimal(18,4) NULL,
    [MakeBuyCode] varchar(10) NULL,
    [PrimaryVendorName] varchar(200) NULL,
    [SecondaryVendorName] varchar(200) NULL,
    [ReplenishmentLeadTime] decimal(18,4) NULL,
    [UsedStorageCube] decimal(18,4) NULL,
    [StandardCost] decimal(18,4) NULL,
    [FobArcPrice] decimal(18,4) NULL,
    [Cubes] decimal(18,4) NULL,
    [LastInvoiceDate] date NULL,
    [InventoryAgeWeeks] int NULL,
    [Aging Bucket <3M Qty] decimal(18,4) NULL,
    [Aging Bucket <6M Qty] decimal(18,4) NULL,
    [Aging Bucket <12M Qty] decimal(18,4) NULL,
    [Aging Bucket >12M Qty] decimal(18,4) NULL,
    [AFIStatus] varchar(20) NULL
);
