-- Generated from live Fabric metadata: SupplyChain_Gold_Warehouse
CREATE TABLE [InventoryHealth_DW].[FactInventoryHealthFutureWeekEnding] (
    [ItemSku] varchar(50) NULL,
    [WarehouseCode] varchar(50) NULL,
    [FutureWeekEnding] date NULL,
    [SnapshotDate] date NULL,
    [TotalInvCommitmentInFuture] decimal(18,4) NULL,
    [ATPQty] decimal(18,4) NULL,
    [IsShortage/Surplus/InStock] varchar(30) NULL,
    [Shortage/SurplusQty] decimal(18,4) NULL,
    [MakeBuyCode] varchar(10) NULL,
    [PrimaryVendorName] varchar(200) NULL,
    [SecondaryVendorName] varchar(200) NULL,
    [ReplenishmentLeadTime] decimal(18,4) NULL,
    [UsedStoreCube] decimal(18,4) NULL,
    [ProjectedRevenueAtRisk] decimal(18,4) NULL,
    [ProjectedWOS] decimal(18,4) NULL,
    [ProjectedInventoryClassification] varchar(30) NULL,
    [AwdQty] decimal(18,4) NULL,
    [SafetyStockTarget] decimal(18,4) NULL,
    [AFIStatus] varchar(20) NULL,
    [Cubes] decimal(18,4) NULL,
    [InventorySnapshotDate] date NULL,
    [SupplyPlanSnapshotDate] date NULL,
    [ATPSnapshotDate] date NULL,
    [FirmDemandQty] decimal(18,4) NULL,
    [NetFcstQty] decimal(18,4) NULL,
    [FirmDemandQtyAtRisk] decimal(18,4) NULL,
    [NetFcstQtyAtRisk] decimal(18,4) NULL,
    [IsActiveItemWhIn7DNext] int NULL,
    [IsActiveItemWhIn14DNext] int NULL,
    [LatestSupplyPlanSnapshotDate] date NULL,
    [AwdAsOfDate] date NULL,
    [AfiStatusAsOfDate] date NULL
);
