-- Generated from live Fabric metadata: SupplyChain_Gold_Warehouse
CREATE TABLE [InventoryHealth_DW].[ProjectedInventoryHealthSubStatus] (
    [ItemSku] varchar(50) NULL,
    [WarehouseCode] varchar(50) NULL,
    [FactAsOfDate] date NULL,
    [FutureWeekEndingDate] date NULL,
    [SupplyPlanSnapshotDate] date NULL,
    [AwdAsOfDate] date NULL,
    [AfiStatusAsOfDate] date NULL,
    [LastInvoiceAsOfDate] date NULL,
    [ProjectedSubStatus] varchar(17) NOT NULL,
    [ProjectedRanking] int NOT NULL,
    [ProjectedInventoryClassificationFinalStatus] varchar(17) NOT NULL,
    [AvgWeeklyDemand] decimal(18,4) NULL,
    [SafetyStockTarget] decimal(18,4) NULL,
    [ProjectedInventoryQty] decimal(18,4) NULL,
    [FirmDemandQty] decimal(18,4) NULL,
    [NetFcstQty] decimal(18,4) NULL,
    [FirmDemandQtyAtRisk] decimal(18,4) NULL,
    [NetFcstQtyAtRisk] decimal(18,4) NULL,
    [IsActiveItemWhIn7DNext] int NULL,
    [IsActiveItemWhIn14DNext] int NULL,
    [AFIStatus] varchar(20) NULL,
    [LastInvoiceDate] date NULL,
    [SupplyPlanSnapshotType] varchar(30) NULL,
    [LatestSupplyPlanSnapshotDate] date NULL,
    [SupplyPlanSnapshotLagDays] int NULL,
    [AwdLagDays] int NULL,
    [AfiStatusLagDays] int NULL,
    [LastInvoiceLagDays] int NULL
);
