-- Physical final table contract: [SupplyChain_Processing_Warehouse].[OpenOrderHistory_Enh].[OpenOrderMonthly]
-- Loaded by ETL_Framework from [SupplyChain_Processing_Warehouse].[OpenOrderHistory_Enh_Wrk].[v_OpenOrderMonthly].
-- Business/source view SQL is documented in ../OpenOrderHistory_Enh_Wrk/v_OpenOrderMonthly.sql.
