-- Generated from live Fabric metadata: Enterprise_Lakehouse
CREATE TABLE [CustomerOrders_AFI].[WarehouseMaster] (
    [Warehouse] varchar(8000) NULL,
    [LocationID] decimal(10,0) NULL,
    [IntransitWarehouse] varchar(8000) NULL,
    [SiteID] varchar(8000) NULL,
    [MROSiteID] varchar(8000) NULL,
    [WarehouseType] varchar(8000) NULL,
    [WarehouseOrderGroup] varchar(8000) NULL,
    [WarehouseSourceID] varchar(8000) NULL,
    [RouteType] varchar(8000) NULL,
    [DefaultPortId] int NULL,
    [Controlled] bit NULL,
    [PrinterName] varchar(8000) NULL,
    [ZebraPrinter] varchar(8000) NULL,
    [SendBolsToManu] varchar(8000) NULL,
    [OrderReleaseMin] int NULL,
    [OrderReleaseMinType] varchar(8000) NULL,
    [DefaultShipId] int NULL,
    [SortOrder] int NULL,
    [AsOverhead] int NULL,
    [AsFreight] int NULL,
    [ContainerDirectWhse] varchar(8000) NULL,
    [ActiveRecord] varchar(8000) NULL,
    [usra] varchar(8000) NULL,
    [dtea] datetime2(6) NULL,
    [usrc] varchar(8000) NULL,
    [dtec] datetime2(6) NULL,
    [WhereMade] varchar(8000) NULL,
    [ManufacturingSite] varchar(8000) NULL,
    [SellableWarehouse] bit NULL
);
