-- Generated from live Fabric metadata: Enterprise_Lakehouse
CREATE TABLE [SupplyChain_Enh].[DemandInventorySnapshotDaily] (
    [dinItem] varchar(8000) NOT NULL,
    [dinWarehouse] varchar(8000) NOT NULL,
    [dinFiscalMonth] decimal(6,0) NOT NULL,
    [dinInvPlanningVendor] varchar(8000) NOT NULL,
    [dinDemandPlanner] varchar(8000) NOT NULL,
    [dinSafetyStock] decimal(9,0) NOT NULL,
    [dinBuildQuantity] decimal(9,0) NOT NULL,
    [dinSnapshot] datetime2(6) NULL,
    [dinIOMinSafetyStock] decimal(9,0) NULL,
    [dinIOMaxSafetyStock] decimal(9,0) NULL,
    [dinIOSafetyStock] decimal(9,0) NULL,
    [dinMakeBuyCode] varchar(8000) NULL,
    [dinPrimaryVendorNumber] varchar(8000) NULL,
    [dinPrimaryVendorName] varchar(8000) NULL,
    [dinPrimaryVendorSplit] varchar(8000) NULL,
    [dinSecondaryVendorNumber] varchar(8000) NULL,
    [dinSecondaryVendorName] varchar(8000) NULL,
    [dinSecondaryVendorSplit] varchar(8000) NULL,
    [dinInvPlanning4thChoice] varchar(8000) NULL,
    [dinInvPlanning1stChoice] varchar(8000) NULL,
    [dinSource1] varchar(8000) NULL,
    [dinOnHandQuantity] decimal(9,0) NULL,
    [dinOrderQuantity] decimal(9,0) NULL,
    [dinAlternanteABCCode1] varchar(8000) NULL,
    [dinAlternanteABCCode3] varchar(8000) NULL,
    [dinInventoryPlanningABCCode] varchar(8000) NULL,
    [usra] varchar(8000) NULL,
    [dtea] datetime2(6) NULL,
    [usrc] varchar(8000) NULL,
    [dtec] datetime2(6) NULL,
    [dinReplenishmentLeadTime] decimal(3,0) NULL
);
