-- Generated from live Fabric metadata: Enterprise_Lakehouse
CREATE TABLE [SupplyChain_Enh].[DemandFulfillmentCommonContainer_Logility] (
    [Item] varchar(8000) NULL,
    [Whse] varchar(8000) NULL,
    [WeekEnding] date NULL,
    [FirmDemand] decimal(10,2) NULL,
    [Netfcst] decimal(10,2) NULL,
    [Firmtfrs] decimal(10,2) NULL,
    [PlannedTfrs] decimal(10,2) NULL,
    [FirmProd] decimal(10,2) NULL,
    [PlannedProd] decimal(10,2) NULL,
    [FirmPos] decimal(10,2) NULL,
    [PlannedPos] decimal(10,2) NULL,
    [InTransitTfrs] decimal(10,2) NULL,
    [OnOrderTfrs] decimal(10,2) NULL,
    [Planned Tfrs] decimal(10,2) NULL,
    [Total Receipts] decimal(10,2) NULL,
    [ShippableInvQty] decimal(10,2) NULL,
    [ShippableInvAmt] decimal(10,2) NULL,
    [MosofSupply] decimal(10,2) NULL,
    [SafetyStockQty] decimal(10,2) NULL,
    [SafetyStockAmt] decimal(10,2) NULL,
    [OnHandQty] decimal(10,2) NULL,
    [OnHandAmt] decimal(10,2) NULL,
    [SI-SSAmt] decimal(10,2) NULL,
    [ItemClass] varchar(8000) NULL,
    [CollClass] varchar(8000) NULL,
    [Series] varchar(8000) NULL,
    [Division] varchar(8000) NULL,
    [ItemStatus] varchar(8000) NULL,
    [FutureStatus] varchar(8000) NULL,
    [StatusChngDate] datetime2(6) NULL,
    [Price] decimal(10,2) NULL,
    [HoldBuy] varchar(8000) NULL,
    [UnSW] varchar(8000) NULL,
    [HRInd] varchar(8000) NULL,
    [ABC] varchar(8000) NULL,
    [KeyItem] varchar(8000) NULL,
    [DerivedFcstFactor] varchar(8000) NULL,
    [SourceKey] varchar(8000) NULL,
    [MakeBuyCode] varchar(8000) NULL,
    [Vendor] varchar(8000) NULL,
    [FcstPlanner] varchar(8000) NULL,
    [DRPPlanner] varchar(8000) NULL,
    [OrderMulitple] varchar(8000) NULL,
    [ProductionMin] varchar(8000) NULL,
    [KitComptUsage] varchar(8000) NULL,
    [CurrencyCode] varchar(8000) NULL,
    [FolderPath] varchar(8000) NULL,
    [Filename] varchar(8000) NULL,
    [FileDate] datetime2(6) NULL,
    [FolderName] varchar(8000) NULL,
    [Country] varchar(8000) NULL,
    [Company] varchar(8000) NULL,
    [ExpressShipFlag] varchar(8000) NULL
);
