-- Generated from live Fabric metadata: Enterprise_Lakehouse
CREATE TABLE [SupplyChain_Enh].[SupplyPlanDetailSnapshotDaily] (
    [spdItem] varchar(8000) NOT NULL,
    [spdWarehouse] varchar(8000) NOT NULL,
    [spdWeekEnding] date NOT NULL,
    [spdBeginingBalance] decimal(10,0) NOT NULL,
    [spdFirmDemands] decimal(10,0) NOT NULL,
    [spdNetForecast] decimal(10,0) NOT NULL,
    [spdFirmTransferOut] decimal(10,0) NOT NULL,
    [spdFirmProduction] decimal(10,0) NOT NULL,
    [spdFirmPurchaseOrders] decimal(10,0) NOT NULL,
    [spdInTransitTransferIn] decimal(10,0) NOT NULL,
    [spdOnOrderTransferIn] decimal(10,0) NOT NULL,
    [spdPlannedTransferIn] decimal(10,0) NOT NULL,
    [spdPlannedTransferOut] decimal(10,0) NOT NULL,
    [spdPlannedProduction] decimal(10,0) NOT NULL,
    [spdPlannedPurchaseOrders] decimal(10,0) NOT NULL,
    [spdTotalReceipts] decimal(10,0) NOT NULL,
    [spdShippableInventory] decimal(10,0) NOT NULL,
    [spdSafetyStock] decimal(10,0) NOT NULL,
    [spdMonthsOfSupply] decimal(10,2) NOT NULL,
    [spdResultantForecast] decimal(10,0) NOT NULL,
    [spdPromotionalLift] decimal(10,0) NOT NULL,
    [spdDemandFulfillment] decimal(10,0) NOT NULL,
    [spdWeeklyPromotionalLift] decimal(10,0) NOT NULL,
    [usra] varchar(8000) NULL,
    [dtea] datetime2(6) NULL,
    [usrc] varchar(8000) NULL,
    [dtec] datetime2(6) NULL
);
