-- Physical final table contract: [SupplyChain_Processing_Warehouse].[ReferenceMaster_Enh].[CustomerShippingLocation]
-- Loaded by ETL_Framework from [SupplyChain_Processing_Warehouse].[ReferenceMaster_Enh_Wrk].[v_CustomerShippingLocation].
-- Business/source view SQL is documented in ../ReferenceMaster_Enh_Wrk/v_CustomerShippingLocation.sql.
