-- Physical final table contract: [SupplyChain_Processing_Warehouse].[ReferenceMaster_Enh].[ForecastHorizon]
-- Loaded by ETL_Framework from [SupplyChain_Processing_Warehouse].[ReferenceMaster_Enh_Wrk].[v_ForecastHorizon].
-- Business/source view SQL is documented in ../ReferenceMaster_Enh_Wrk/v_ForecastHorizon.sql.
