-- Target database: SupplyChain_Processing_Warehouse
-- Mart: forecast_accuracy
-- Wave order: Silver W03 derived forecast table
-- Generated by 03_operations/tools/generate_wave_sps.py
CREATE OR ALTER PROCEDURE [dbo].[Usp_Refresh_ForecastAccuracy_Silver_W03]
AS
BEGIN
    SET NOCOUNT ON;

    EXEC [ETL_Framework].[DW_Developer].[usp_RefreshCuratedTableFromView]
        'SupplyChain_Processing_Warehouse', 'ForecastHistory_Enh', 'NaiveForecastMonthly';
END;
