-- Target database: SupplyChain_Processing_Warehouse
-- Mart: forecast_accuracy
-- Wave order: Silver W01 line-level tables
-- Generated by 03_operations/tools/generate_wave_sps.py
CREATE OR ALTER PROCEDURE [dbo].[Usp_Refresh_ForecastAccuracy_Silver_W01]
AS
BEGIN
    SET NOCOUNT ON;

    EXEC [ETL_Framework].[DW_Developer].[usp_RefreshCuratedTableFromView]
        'SupplyChain_Processing_Warehouse', 'SalesHistory_Enh', 'InvoiceDetailLineLevel';

    EXEC [ETL_Framework].[DW_Developer].[usp_RefreshCuratedTableFromView]
        'SupplyChain_Processing_Warehouse', 'OpenOrderHistory_Enh', 'OpenOrderLineLevel';
END;
