-- Target database: SupplyChain_Processing_Warehouse
-- Mart: forecast_accuracy
-- Wave order: Silver W02 aggregate tables
-- Generated by 03_operations/tools/generate_wave_sps.py
CREATE OR ALTER PROCEDURE [dbo].[Usp_Refresh_ForecastAccuracy_Silver_W02]
AS
BEGIN
    SET NOCOUNT ON;

    EXEC [ETL_Framework].[DW_Developer].[usp_RefreshCuratedTableFromView]
        'SupplyChain_Processing_Warehouse', 'SalesHistory_Enh', 'ActualDemandMonthly';

    EXEC [ETL_Framework].[DW_Developer].[usp_RefreshCuratedTableFromView]
        'SupplyChain_Processing_Warehouse', 'SalesHistory_Enh', 'ActualDemandWeekly';

    EXEC [ETL_Framework].[DW_Developer].[usp_RefreshCuratedTableFromView]
        'SupplyChain_Processing_Warehouse', 'SalesHistory_Enh', 'InvoiceWeekly';

    EXEC [ETL_Framework].[DW_Developer].[usp_UpdateCuratedTableFromView_DateRange]
        'SupplyChain_Processing_Warehouse', 'ForecastHistory_Enh', 'ForecastDemandMonthly', 'Snapshot', 'Snapshot', -30;

    EXEC [ETL_Framework].[DW_Developer].[usp_RefreshCuratedTableFromView]
        'SupplyChain_Processing_Warehouse', 'OpenOrderHistory_Enh', 'OpenOrderMonthly';
END;
