-- Physical final table contract: [SupplyChain_Gold_Warehouse].[Shared_DW].[DimWarehouse]
-- Loaded by ETL_Framework from [SupplyChain_Gold_Warehouse].[Shared_DW_Wrk].[v_DimWarehouse].
-- Business/source view SQL is documented in ../Shared_DW_Wrk/v_DimWarehouse.sql.
