-- Enterprise_Lakehouse.ItemMaster_AFI.AITMCLS
-- Layer: Bronze/source shortcut reference for mart `forecast_accuracy`.
-- Status: live active source reference from current Fabric SQL module definitions.
-- This is not a local view/table definition in this repo.
