-- Enterprise_Lakehouse.Wholesale_Codis_AFI.EXTORIT
-- Layer: Bronze/source shortcut reference for mart `forecast_accuracy`.
-- Status: live active source reference from current Fabric SQL module definitions.
-- This is not a local view/table definition in this repo.
