-- Generated from live Fabric metadata: Enterprise_Lakehouse
CREATE TABLE [Wholesale_Codis_AFI].[AshleyWarehouseMaster] (
    [wmaWarehouse] varchar(8000) NULL,
    [wmaLocationId] decimal(10,0) NULL,
    [wmaIntransitWarehouse] varchar(8000) NULL,
    [wmaSiteId] varchar(8000) NULL,
    [wmaMROSiteId] varchar(8000) NULL,
    [wmaWarehouseType] varchar(8000) NULL,
    [wmaWarehouseOrderGroup] varchar(8000) NULL,
    [wmaWarehouseSourceId] varchar(8000) NULL,
    [wmaRouteType] varchar(8000) NULL,
    [wmaDefaultPortId] int NULL,
    [wmaControlled] bit NULL,
    [wmaPrinterName] varchar(8000) NULL,
    [wmaZebraPrinter] varchar(8000) NULL,
    [wmaSendBolsToManu] varchar(8000) NULL,
    [wmaOrderReleaseMin] int NULL,
    [wmaOrderReleaseMinType] varchar(8000) NULL,
    [wmaDefaultShipId] int NULL,
    [wmaSortOrder] int NULL,
    [wmaAsOverhead] int NULL,
    [wmaAsFreight] int NULL,
    [wmaContainerDirectWhse] varchar(8000) NULL,
    [acrec] varchar(8000) NULL,
    [usra] varchar(8000) NULL,
    [dtea] datetime2(6) NULL,
    [usrc] varchar(8000) NULL,
    [dtec] datetime2(6) NULL,
    [wmaWhereMade] varchar(8000) NULL,
    [wmaManufacturingSite] varchar(8000) NULL,
    [wmaSellableWarehouse] bit NULL
);
