-- Generated from live Fabric metadata: Enterprise_Lakehouse
CREATE TABLE [Wholesale_Codis_AFI].[EXTORD] (
    [XORDNO] varchar(8000) NULL,
    [RQSDAT] decimal(8,0) NULL,
    [ORDUSE] varchar(8000) NULL,
    [ORDARR] varchar(8000) NULL,
    [ADVTSP] varchar(8000) NULL,
    [NOSETS] decimal(3,0) NULL,
    [ORDREF] varchar(8000) NULL,
    [ORDLNK] decimal(6,0) NULL,
    [CSRPID] decimal(5,0) NULL,
    [EXTCTY] varchar(8000) NULL,
    [EXTSTE] varchar(8000) NULL,
    [OTTYP1] varchar(8000) NULL,
    [OTTYP2] varchar(8000) NULL,
    [OTTYP3] varchar(8000) NULL,
    [OTTYP4] varchar(8000) NULL,
    [MNTCNT] decimal(3,0) NULL,
    [FRZDAT] decimal(8,0) NULL,
    [SHPNAM] varchar(8000) NULL,
    [WHSE] varchar(8000) NULL,
    [CUSTNO] varchar(8000) NOT NULL,
    [SHPTO#] varchar(8000) NOT NULL,
    [TKNDAT] decimal(8,0) NULL,
    [TRPNO] decimal(6,0) NULL,
    [HDATE] decimal(8,0) NULL,
    [DROP#] decimal(2,0) NULL,
    [TRIP#] decimal(6,0) NULL,
    [CREDVW] varchar(8000) NULL,
    [APVCHK] varchar(8000) NULL,
    [APPROV] varchar(8000) NULL,
    [ORDUSR] varchar(8000) NULL,
    [HLDUSR] varchar(8000) NULL,
    [TERRCD] varchar(8000) NULL,
    [CONTAC] varchar(8000) NULL,
    [PHONE#] varchar(8000) NULL,
    [REFNUM] decimal(6,0) NULL,
    [RCVCSH] varchar(8000) NULL,
    [CAPRDT] decimal(8,0) NULL,
    [CROVRD] varchar(8000) NULL,
    [CROVDT] decimal(8,0) NULL,
    [CRANOV] varchar(8000) NULL,
    [CBDDAT] decimal(8,0) NULL,
    [USRMNT] varchar(8000) NULL,
    [DATMNT] decimal(8,0) NULL,
    [TIMMNT] decimal(6,0) NULL,
    [ORTYPE] varchar(8000) NULL,
    [COMMCO] varchar(8000) NULL,
    [DSCNCO] varchar(8000) NULL,
    [PRICCO] varchar(8000) NULL,
    [FRGHCO] varchar(8000) NULL,
    [ZIPCOD] varchar(8000) NULL,
    [ARZONE] varchar(8000) NULL,
    [ARSEQ] decimal(2,0) NULL,
    [ARDATE] decimal(8,0) NULL,
    [PRMNBR] varchar(8000) NULL
);
