-- Source: SupplyChain_Warehouse.SCP_Core_Wrk.v_DimFiscalCalendar
-- Generated from INFORMATION_SCHEMA.COLUMNS.
-- This is a logical schema snapshot; review Fabric physical options before execution.
CREATE TABLE [SCP_Core_Wrk].[v_DimFiscalCalendar] (
    [Transaction Date] date NOT NULL,
    [Integer Date] int NOT NULL,
    [Mapics Date] int NULL,
    [Day of Week] varchar(8000) NULL,
    [Fiscal Week Num] int NULL,
    [FW Desc] varchar(17) NOT NULL,
    [Fiscal Year Week Num] int NULL,
    [Fiscal Month Num] int NULL,
    [FM Desc] varchar(17) NOT NULL,
    [Fiscal Month Name] nvarchar(4000) NULL,
    [Fiscal Year Month Num] int NULL,
    [Fiscal Month Year Desc] nvarchar(4000) NULL,
    [Fiscal Month (calendar start)] date NULL,
    [Fiscal Quarter Num] int NULL,
    [FQ Desc] varchar(17) NOT NULL,
    [Fiscal Year Half Num] smallint NULL,
    [Fiscal Half Num] int NULL,
    [FH Desc] varchar(17) NOT NULL,
    [Fiscal Year] smallint NULL,
    [FY Desc] varchar(9) NOT NULL,
    [Fiscal Week Start] date NULL,
    [Fiscal Week End] date NULL,
    [Fiscal Month Start] date NULL,
    [Fiscal Month End] date NULL,
    [Fiscal Year Start] date NULL,
    [Fiscal Year End] date NULL,
    [Holiday Indicator] varchar(8000) NULL,
    [Holiday Name] varchar(8000) NULL,
    [WeekdayWeekend] varchar(8000) NULL,
    [Calendar Week Num] int NULL,
    [Calendar Month Num] int NULL,
    [Calendar Quarter Num] int NULL,
    [Calendar Year] smallint NULL,
    [Fiscal Day Indicator] int NULL,
    [Fiscal Week Indicator] int NULL,
    [Fiscal Month Indicator] int NULL,
    [Fiscal Quarter Indicator] int NULL,
    [Fiscal Year Indicator] int NULL
);
