-- SalesHistory_Enh_Wrk.v_InvoiceDetailLineLevel
CREATE   VIEW [SalesHistory_Enh_Wrk].[v_InvoiceDetailLineLevel] AS
WITH __bob_source AS (
SELECT 
    INV.InvoiceNumber                                AS InvoiceID,
    INV.ExtendedInvoiceNumber                        AS InvoiceExtended,
    INV.OrderNumber                                  AS OrderID,
    INV.ItemSequence                                 AS ItemSequenceNum,
    INV.CustomerNumber                               AS Customer,
    INV.ShiptoNumber                                 AS ShipToCode,
    UPPER(RTRIM(CASE WHEN INV.ShiptoNumber IS NULL OR TRIM(INV.ShiptoNumber)='' THEN TRIM(INV.CustomerNumber) ELSE CONCAT(TRIM(INV.CustomerNumber),'-',TRIM(INV.ShiptoNumber)) END)) AS AccountShipTo,
    INV.ItemSKU,
    INV.Warehouse                                    AS WarehouseCode,
    UPPER(CG.CustomerGroupCode)                      AS CustomerGroupCode,
    IH.LeadTime                                      AS LeadTimeDaysNum,
    INV.QuantityShipped                              AS QtyShipped,
    INV.QuantityOrdered                              AS QtyOrdered,
    INV.QuantityBackOrdered                          AS QtyBackordered,
    INV.InvoiceAmount                                AS AmtInvoice,
    INV.NetSales                                     AS AmtNetSales,
    INV.Price                                        AS AmtPrice,
    INV.StandardPrice                                AS AmtStandardPrice,
    INV.ContractPrice                                AS AmtContractPrice,
    INV.Discount                                     AS AmtDiscount,
    INV.PriceAdjustment                              AS AmtPriceAdjustment,
    INV.Freight                                      AS AmtFreight,
    INV.InvoiceDate,
    INV.OrderDate,
    INV.RequestDate                                  AS Request,
    INV.CurrentRequestDate                           AS CurrentRequest,
    INV.CurrentPromiseDate                           AS CurrentPromise,
    INV.OriginalRequestDate                          AS OriginalRequest,
    INV.OriginalPromiseDate                          AS OriginalPromise,
    INV.PromisedDelivery,
    INV.DeliveryDate                                 AS Delivery,
    INV.ActualDelivery,
    INV.OrderType                                    AS OrderTypeCode,
    INV.OrderType3                                   AS OrderType3Code,
    INV.CreditCode,
    INV.ItemClass                                    AS ItemClassCode,
    INV.OrderItemStatus                              AS OrderItemStatusCode
FROM [Enterprise_Lakehouse].[SalesHistory_AFI_Enh].[InvoiceDetail] AS INV
LEFT JOIN [Enterprise_Lakehouse].[SalesHistory_AFI_Enh].[InvoiceHeader] AS IH
       ON INV.InvoiceNumber=IH.InvoiceNumber AND INV.InvoiceDate=IH.InvoiceDate AND INV.OrderDate=IH.OrderDate AND INV.OrderNumber=IH.OrderNumber
LEFT JOIN ReferenceMaster_Enh.CustomerAccountGroup AS CG ON CG.Customer=INV.CustomerNumber
)
SELECT
    [InvoiceID] = src.[InvoiceID],
    [InvoiceExtended] = src.[InvoiceExtended],
    [OrderID] = src.[OrderID],
    [ItemSequenceNum] = src.[ItemSequenceNum],
    [Customer] = src.[Customer],
    [ShipToCode] = src.[ShipToCode],
    [AccountShipTo] = src.[AccountShipTo],
    [ItemSKU] = src.[ItemSKU],
    [WarehouseCode] = src.[WarehouseCode],
    [CustomerGroupCode] = src.[CustomerGroupCode],
    [LeadTimeDaysNum] = src.[LeadTimeDaysNum],
    [QtyShipped] = src.[QtyShipped],
    [QtyOrdered] = src.[QtyOrdered],
    [QtyBackordered] = src.[QtyBackordered],
    [AmtInvoice] = src.[AmtInvoice],
    [AmtNetSales] = src.[AmtNetSales],
    [AmtPrice] = src.[AmtPrice],
    [AmtStandardPrice] = src.[AmtStandardPrice],
    [AmtContractPrice] = src.[AmtContractPrice],
    [AmtDiscount] = src.[AmtDiscount],
    [AmtPriceAdjustment] = src.[AmtPriceAdjustment],
    [AmtFreight] = src.[AmtFreight],
    [InvoiceDate] = src.[InvoiceDate],
    [OrderDate] = src.[OrderDate],
    [Request] = src.[Request],
    [CurrentRequest] = src.[CurrentRequest],
    [CurrentPromise] = src.[CurrentPromise],
    [OriginalRequest] = src.[OriginalRequest],
    [OriginalPromise] = src.[OriginalPromise],
    [PromisedDelivery] = src.[PromisedDelivery],
    [Delivery] = src.[Delivery],
    [ActualDelivery] = src.[ActualDelivery],
    [OrderTypeCode] = src.[OrderTypeCode],
    [OrderType3Code] = src.[OrderType3Code],
    [CreditCode] = src.[CreditCode],
    [ItemClassCode] = src.[ItemClassCode],
    [OrderItemStatusCode] = src.[OrderItemStatusCode],
    [LoadDT] = CAST(SYSUTCDATETIME() AS datetime2(6))
FROM __bob_source AS src;
