-- Target database: SupplyChain_Processing_Warehouse
-- Mart: shared
-- Wave order: Shared W01 Staging prerequisites
-- Generated by 03_operations/tools/generate_wave_sps.py
CREATE OR ALTER PROCEDURE [dbo].[Usp_Refresh_Shared_Staging]
AS
BEGIN
    SET NOCOUNT ON;

    EXEC [ETL_Framework].[DW_Developer].[usp_RefreshCuratedTableFromView]
        'SupplyChain_Processing_Warehouse', 'Staging', 'DemandForecastSnapshotDaily';
END;
