-- Generated from live Fabric metadata: Enterprise_Lakehouse
CREATE TABLE [MasterData_DW].[DimDate] (
    [DateKey] int NOT NULL,
    [MapicsDate] int NULL,
    [DateID] date NOT NULL,
    [DateTimeID] date NOT NULL,
    [CalendarDate] date NOT NULL,
    [CalendarDateName] varchar(8000) NULL,
    [CalendarDateIndicator] int NULL,
    [CalendarWeek] int NULL,
    [CalendarWeekIndicator] int NULL,
    [CalendarWeekYear] int NULL,
    [CalendarWeekYearName] varchar(8000) NULL,
    [CalendarDayOfWeek] int NULL,
    [CalendarDayOfWeekName] varchar(8000) NULL,
    [CalendarWeekFirstDate] date NULL,
    [CalendarWeekLastDate] date NULL,
    [CalendarMonth] int NULL,
    [CalendarMonthIndicator] int NULL,
    [CalendarMonthYear] int NULL,
    [CalendarMonthName] varchar(8000) NULL,
    [CalendarMonthYearName] varchar(8000) NULL,
    [CalendarDayOfMonth] int NULL,
    [CalendarWeekOfMonth] int NULL,
    [CalendarMonthFirstDate] date NULL,
    [CalendarMonthLastDate] date NULL,
    [CalendarQuarter] int NULL,
    [CalendarQuarterName] varchar(8000) NULL,
    [CalendarQuarterIndicator] int NULL,
    [CalendarQuarterYear] smallint NULL,
    [CalendarQuarterYearName] varchar(8000) NULL,
    [CalendarSemester] int NULL,
    [CalendarSemesterYear] smallint NULL,
    [CalendarYear] smallint NULL,
    [CalendarYearName] varchar(8000) NULL,
    [CalendarYearIndicator] int NULL,
    [CalendarDayOfYear] smallint NULL,
    [FiscalDate] date NULL,
    [FiscalDateName] varchar(8000) NULL,
    [FiscalDateIndicator] int NULL,
    [FiscalWeek] int NULL,
    [FiscalWeekIndicator] int NULL,
    [FiscalDayOfWeek] int NULL,
    [FiscalDayOfWeekName] varchar(8000) NULL,
    [FiscalWeekYear] int NULL,
    [FiscalWeekYearName] varchar(8000) NULL,
    [FiscalWeekFirstDate] date NULL,
    [FiscalWeekLastDate] date NULL,
    [FiscalMonth] int NULL,
    [FiscalMonthIndicator] int NULL,
    [FiscalMonthYear] int NULL,
    [FiscalMonthName] varchar(8000) NULL,
    [FiscalMonthYearName] varchar(8000) NULL,
    [FiscalDayOfMonth] int NULL,
    [FiscalWeekOfMonth] int NULL,
    [FiscalMonthFirstDate] date NULL,
    [FiscalMonthLastDate] date NULL,
    [FiscalQuarter] int NULL,
    [FiscalQuarterName] varchar(8000) NULL,
    [FiscalQuarterIndicator] int NULL,
    [FiscalQuarterYear] smallint NULL,
    [FiscalQuarterYearName] varchar(8000) NULL,
    [FiscalSemester] int NULL,
    [FiscalSemesterYear] smallint NULL,
    [FiscalYear] smallint NULL,
    [FiscalYearName] varchar(8000) NULL,
    [FiscalYearIndicator] int NULL,
    [FiscalDayOfYear] smallint NULL,
    [FiscalYearFirstDate] date NULL,
    [FiscalYearLastDate] date NULL,
    [HolidayIndicator] varchar(8000) NULL,
    [HolidayName] varchar(8000) NULL,
    [WorkingDayIndicator] varchar(8000) NULL,
    [WeekdayWeekend] varchar(8000) NULL
);
