-- DQ rerun template for Enterprise_Lakehouse.SupplyChain_Enh.DemandInventorySnapshotDaily
-- Generated by lineage_compiler. Review key grain before executing against live Fabric.

SELECT COUNT_BIG(*) AS row_count
FROM Enterprise_Lakehouse.SupplyChain_Enh.DemandInventorySnapshotDaily;

SELECT [dinSnapshot], [dinItem], [dinWarehouse], COUNT_BIG(*) AS duplicate_count
FROM Enterprise_Lakehouse.SupplyChain_Enh.DemandInventorySnapshotDaily
GROUP BY [dinSnapshot], [dinItem], [dinWarehouse]
HAVING COUNT_BIG(*) > 1;

SELECT COUNT_BIG(*) AS null_blank_key_rows
FROM Enterprise_Lakehouse.SupplyChain_Enh.DemandInventorySnapshotDaily
WHERE [dinSnapshot] IS NULL OR TRY_CAST([dinSnapshot] AS VARCHAR(4000)) = '' OR [dinItem] IS NULL OR TRY_CAST([dinItem] AS VARCHAR(4000)) = '' OR [dinWarehouse] IS NULL OR TRY_CAST([dinWarehouse] AS VARCHAR(4000)) = '';

