-- DQ rerun template for Enterprise_Lakehouse.Wholesale_ProductSourcing_AFI.CustomerGrouping
-- Generated by lineage_compiler. Review key grain before executing against live Fabric.

SELECT COUNT_BIG(*) AS row_count
FROM Enterprise_Lakehouse.Wholesale_ProductSourcing_AFI.CustomerGrouping;

SELECT [CustomerNumber], [CustomerGroup], COUNT_BIG(*) AS duplicate_count
FROM Enterprise_Lakehouse.Wholesale_ProductSourcing_AFI.CustomerGrouping
GROUP BY [CustomerNumber], [CustomerGroup]
HAVING COUNT_BIG(*) > 1;

SELECT COUNT_BIG(*) AS null_blank_key_rows
FROM Enterprise_Lakehouse.Wholesale_ProductSourcing_AFI.CustomerGrouping
WHERE [CustomerNumber] IS NULL OR TRY_CAST([CustomerNumber] AS VARCHAR(4000)) = '' OR [CustomerGroup] IS NULL OR TRY_CAST([CustomerGroup] AS VARCHAR(4000)) = '';

