-- DQ rerun template for Enterprise_Lakehouse.Manufacturing_Inventory_AFI.TFRHDR
-- Generated by lineage_compiler. Review key grain before executing against live Fabric.

SELECT COUNT_BIG(*) AS row_count
FROM Enterprise_Lakehouse.Manufacturing_Inventory_AFI.TFRHDR;

SELECT [HTFRNO], COUNT_BIG(*) AS duplicate_count
FROM Enterprise_Lakehouse.Manufacturing_Inventory_AFI.TFRHDR
GROUP BY [HTFRNO]
HAVING COUNT_BIG(*) > 1;

SELECT COUNT_BIG(*) AS null_blank_key_rows
FROM Enterprise_Lakehouse.Manufacturing_Inventory_AFI.TFRHDR
WHERE [HTFRNO] IS NULL OR TRY_CAST([HTFRNO] AS VARCHAR(4000)) = '';

