-- DQ rerun template for Enterprise_Lakehouse.Purchasing_AFI.VendorMaster
-- Generated by lineage_compiler. Review key grain before executing against live Fabric.

SELECT COUNT_BIG(*) AS row_count
FROM Enterprise_Lakehouse.Purchasing_AFI.VendorMaster;

SELECT [VendorNumber], COUNT_BIG(*) AS duplicate_count
FROM Enterprise_Lakehouse.Purchasing_AFI.VendorMaster
GROUP BY [VendorNumber]
HAVING COUNT_BIG(*) > 1;

SELECT COUNT_BIG(*) AS null_blank_key_rows
FROM Enterprise_Lakehouse.Purchasing_AFI.VendorMaster
WHERE [VendorNumber] IS NULL OR TRY_CAST([VendorNumber] AS VARCHAR(4000)) = '';

