-- DQ rerun template for Enterprise_Lakehouse.Inventory_Enh_History.ItemBalance
-- Generated by lineage_compiler. Review key grain before executing against live Fabric.

SELECT COUNT_BIG(*) AS row_count
FROM Enterprise_Lakehouse.Inventory_Enh_History.ItemBalance;

SELECT [ItemNumber], [Warehouse], [DateWeekEnding], COUNT_BIG(*) AS duplicate_count
FROM Enterprise_Lakehouse.Inventory_Enh_History.ItemBalance
GROUP BY [ItemNumber], [Warehouse], [DateWeekEnding]
HAVING COUNT_BIG(*) > 1;

SELECT COUNT_BIG(*) AS null_blank_key_rows
FROM Enterprise_Lakehouse.Inventory_Enh_History.ItemBalance
WHERE [ItemNumber] IS NULL OR TRY_CAST([ItemNumber] AS VARCHAR(4000)) = '' OR [Warehouse] IS NULL OR TRY_CAST([Warehouse] AS VARCHAR(4000)) = '' OR [DateWeekEnding] IS NULL OR TRY_CAST([DateWeekEnding] AS VARCHAR(4000)) = '';

