-- DQ rerun template for Enterprise_Lakehouse.ItemMaster_AFI.ITEMBL
-- Generated by lineage_compiler. Review key grain before executing against live Fabric.

SELECT COUNT_BIG(*) AS row_count
FROM Enterprise_Lakehouse.ItemMaster_AFI.ITEMBL;

SELECT [ITNBR], [MDATE], COUNT_BIG(*) AS duplicate_count
FROM Enterprise_Lakehouse.ItemMaster_AFI.ITEMBL
GROUP BY [ITNBR], [MDATE]
HAVING COUNT_BIG(*) > 1;

SELECT COUNT_BIG(*) AS null_blank_key_rows
FROM Enterprise_Lakehouse.ItemMaster_AFI.ITEMBL
WHERE [ITNBR] IS NULL OR TRY_CAST([ITNBR] AS VARCHAR(4000)) = '' OR [MDATE] IS NULL OR TRY_CAST([MDATE] AS VARCHAR(4000)) = '';

