-- DQ rerun template for Enterprise_Lakehouse.SupplyChain_Enh.DemandFulfillmentCommonContainer_Logility
-- Generated by lineage_compiler. Review key grain before executing against live Fabric.

SELECT COUNT_BIG(*) AS row_count
FROM Enterprise_Lakehouse.SupplyChain_Enh.DemandFulfillmentCommonContainer_Logility;

SELECT [WeekEnding], [Item], COUNT_BIG(*) AS duplicate_count
FROM Enterprise_Lakehouse.SupplyChain_Enh.DemandFulfillmentCommonContainer_Logility
GROUP BY [WeekEnding], [Item]
HAVING COUNT_BIG(*) > 1;

SELECT COUNT_BIG(*) AS null_blank_key_rows
FROM Enterprise_Lakehouse.SupplyChain_Enh.DemandFulfillmentCommonContainer_Logility
WHERE [WeekEnding] IS NULL OR TRY_CAST([WeekEnding] AS VARCHAR(4000)) = '' OR [Item] IS NULL OR TRY_CAST([Item] AS VARCHAR(4000)) = '';

