-- DQ rerun template for Enterprise_Lakehouse.SupplyChain_Enh.PurchaseOrderSnapshot
-- Generated by lineage_compiler. Review key grain before executing against live Fabric.

SELECT COUNT_BIG(*) AS row_count
FROM Enterprise_Lakehouse.SupplyChain_Enh.PurchaseOrderSnapshot;

SELECT [posSnapshot], [posItNbr], [posWhse], [posVndnr], [posDueDt], COUNT_BIG(*) AS duplicate_count
FROM Enterprise_Lakehouse.SupplyChain_Enh.PurchaseOrderSnapshot
GROUP BY [posSnapshot], [posItNbr], [posWhse], [posVndnr], [posDueDt]
HAVING COUNT_BIG(*) > 1;

SELECT COUNT_BIG(*) AS null_blank_key_rows
FROM Enterprise_Lakehouse.SupplyChain_Enh.PurchaseOrderSnapshot
WHERE [posSnapshot] IS NULL OR TRY_CAST([posSnapshot] AS VARCHAR(4000)) = '' OR [posItNbr] IS NULL OR TRY_CAST([posItNbr] AS VARCHAR(4000)) = '' OR [posWhse] IS NULL OR TRY_CAST([posWhse] AS VARCHAR(4000)) = '' OR [posVndnr] IS NULL OR TRY_CAST([posVndnr] AS VARCHAR(4000)) = '' OR [posDueDt] IS NULL OR TRY_CAST([posDueDt] AS VARCHAR(4000)) = '';

