-- DQ rerun template for Enterprise_Lakehouse.Wholesale_Codis_AFI.AshleyWarehouseMaster
-- Generated by lineage_compiler. Review key grain before executing against live Fabric.

SELECT COUNT_BIG(*) AS row_count
FROM Enterprise_Lakehouse.Wholesale_Codis_AFI.AshleyWarehouseMaster;

-- Grain duplicate check skipped: no key_columns available.

-- Null/blank key check skipped: no key_columns available.

