-- DQ rerun template for Enterprise_Lakehouse.SupplyChain_Enh.SupplyPlanDetailSnapshotDaily
-- Generated by lineage_compiler. Review key grain before executing against live Fabric.

SELECT COUNT_BIG(*) AS row_count
FROM Enterprise_Lakehouse.SupplyChain_Enh.SupplyPlanDetailSnapshotDaily;

SELECT [dtea], [spdItem], [spdWarehouse], [spdWeekEnding], COUNT_BIG(*) AS duplicate_count
FROM Enterprise_Lakehouse.SupplyChain_Enh.SupplyPlanDetailSnapshotDaily
GROUP BY [dtea], [spdItem], [spdWarehouse], [spdWeekEnding]
HAVING COUNT_BIG(*) > 1;

SELECT COUNT_BIG(*) AS null_blank_key_rows
FROM Enterprise_Lakehouse.SupplyChain_Enh.SupplyPlanDetailSnapshotDaily
WHERE [dtea] IS NULL OR TRY_CAST([dtea] AS VARCHAR(4000)) = '' OR [spdItem] IS NULL OR TRY_CAST([spdItem] AS VARCHAR(4000)) = '' OR [spdWarehouse] IS NULL OR TRY_CAST([spdWarehouse] AS VARCHAR(4000)) = '' OR [spdWeekEnding] IS NULL OR TRY_CAST([spdWeekEnding] AS VARCHAR(4000)) = '';

