-- DQ rerun template for Enterprise_Lakehouse.SupplyChain_Enh.ATPWeekEnding
-- Generated by lineage_compiler. Review key grain before executing against live Fabric.

SELECT COUNT_BIG(*) AS row_count
FROM Enterprise_Lakehouse.SupplyChain_Enh.ATPWeekEnding;

SELECT [WeekEnding], [RunDate], [InsertedDate], [ItemSKU], [Warehouse], [AFIFinanceDivision], COUNT_BIG(*) AS duplicate_count
FROM Enterprise_Lakehouse.SupplyChain_Enh.ATPWeekEnding
GROUP BY [WeekEnding], [RunDate], [InsertedDate], [ItemSKU], [Warehouse], [AFIFinanceDivision]
HAVING COUNT_BIG(*) > 1;

SELECT COUNT_BIG(*) AS null_blank_key_rows
FROM Enterprise_Lakehouse.SupplyChain_Enh.ATPWeekEnding
WHERE [WeekEnding] IS NULL OR TRY_CAST([WeekEnding] AS VARCHAR(4000)) = '' OR [RunDate] IS NULL OR TRY_CAST([RunDate] AS VARCHAR(4000)) = '' OR [InsertedDate] IS NULL OR TRY_CAST([InsertedDate] AS VARCHAR(4000)) = '' OR [ItemSKU] IS NULL OR TRY_CAST([ItemSKU] AS VARCHAR(4000)) = '' OR [Warehouse] IS NULL OR TRY_CAST([Warehouse] AS VARCHAR(4000)) = '' OR [AFIFinanceDivision] IS NULL OR TRY_CAST([AFIFinanceDivision] AS VARCHAR(4000)) = '';

