-- DQ rerun template for Enterprise_Lakehouse.Manufacturing_ProductionPlanning_AFI.MOMAST
-- Generated by lineage_compiler. Review key grain before executing against live Fabric.

SELECT COUNT_BIG(*) AS row_count
FROM Enterprise_Lakehouse.Manufacturing_ProductionPlanning_AFI.MOMAST;

SELECT [ORDNO], COUNT_BIG(*) AS duplicate_count
FROM Enterprise_Lakehouse.Manufacturing_ProductionPlanning_AFI.MOMAST
GROUP BY [ORDNO]
HAVING COUNT_BIG(*) > 1;

SELECT COUNT_BIG(*) AS null_blank_key_rows
FROM Enterprise_Lakehouse.Manufacturing_ProductionPlanning_AFI.MOMAST
WHERE [ORDNO] IS NULL OR TRY_CAST([ORDNO] AS VARCHAR(4000)) = '';

