-- DQ rerun template for Enterprise_Lakehouse.SupplyChain_Enh.DemandForecastSnapshotDaily
-- Generated by lineage_compiler. Review key grain before executing against live Fabric.

SELECT COUNT_BIG(*) AS row_count
FROM Enterprise_Lakehouse.SupplyChain_Enh.DemandForecastSnapshotDaily;

SELECT [dfcSnapshot], [dfcItem], [dfcWarehouse], COUNT_BIG(*) AS duplicate_count
FROM Enterprise_Lakehouse.SupplyChain_Enh.DemandForecastSnapshotDaily
GROUP BY [dfcSnapshot], [dfcItem], [dfcWarehouse]
HAVING COUNT_BIG(*) > 1;

SELECT COUNT_BIG(*) AS null_blank_key_rows
FROM Enterprise_Lakehouse.SupplyChain_Enh.DemandForecastSnapshotDaily
WHERE [dfcSnapshot] IS NULL OR TRY_CAST([dfcSnapshot] AS VARCHAR(4000)) = '' OR [dfcItem] IS NULL OR TRY_CAST([dfcItem] AS VARCHAR(4000)) = '' OR [dfcWarehouse] IS NULL OR TRY_CAST([dfcWarehouse] AS VARCHAR(4000)) = '';

