-- DQ rerun template for Enterprise_Lakehouse.MasterData_ProductKnowledge.Item_ENV
-- Generated by lineage_compiler. Review key grain before executing against live Fabric.

SELECT COUNT_BIG(*) AS row_count
FROM Enterprise_Lakehouse.MasterData_ProductKnowledge.Item_ENV;

-- Grain duplicate check skipped: no key_columns available.

-- Null/blank key check skipped: no key_columns available.

