-- DQ rerun template for Enterprise_Lakehouse.SalesHistory_AFI_Enh.InvoiceDetail
-- Generated by lineage_compiler. Review key grain before executing against live Fabric.

SELECT COUNT_BIG(*) AS row_count
FROM Enterprise_Lakehouse.SalesHistory_AFI_Enh.InvoiceDetail;

SELECT [InvoiceNumber], [ItemSequence], [LineReleaseNumber], [OriginalSequenceNumber], [ItemSKU], COUNT_BIG(*) AS duplicate_count
FROM Enterprise_Lakehouse.SalesHistory_AFI_Enh.InvoiceDetail
GROUP BY [InvoiceNumber], [ItemSequence], [LineReleaseNumber], [OriginalSequenceNumber], [ItemSKU]
HAVING COUNT_BIG(*) > 1;

SELECT COUNT_BIG(*) AS null_blank_key_rows
FROM Enterprise_Lakehouse.SalesHistory_AFI_Enh.InvoiceDetail
WHERE [InvoiceNumber] IS NULL OR TRY_CAST([InvoiceNumber] AS VARCHAR(4000)) = '' OR [ItemSequence] IS NULL OR TRY_CAST([ItemSequence] AS VARCHAR(4000)) = '' OR [LineReleaseNumber] IS NULL OR TRY_CAST([LineReleaseNumber] AS VARCHAR(4000)) = '' OR [OriginalSequenceNumber] IS NULL OR TRY_CAST([OriginalSequenceNumber] AS VARCHAR(4000)) = '' OR [ItemSKU] IS NULL OR TRY_CAST([ItemSKU] AS VARCHAR(4000)) = '';

