-- DQ rerun template for Enterprise_Lakehouse.Wholesale_Codis_AFI.codatan
-- Generated by lineage_compiler. Review key grain before executing against live Fabric.

SELECT COUNT_BIG(*) AS row_count
FROM Enterprise_Lakehouse.Wholesale_Codis_AFI.codatan;

SELECT [ITNBR], COUNT_BIG(*) AS duplicate_count
FROM Enterprise_Lakehouse.Wholesale_Codis_AFI.codatan
GROUP BY [ITNBR]
HAVING COUNT_BIG(*) > 1;

SELECT COUNT_BIG(*) AS null_blank_key_rows
FROM Enterprise_Lakehouse.Wholesale_Codis_AFI.codatan
WHERE [ITNBR] IS NULL OR TRY_CAST([ITNBR] AS VARCHAR(4000)) = '';

