-- DQ rerun template for Enterprise_Lakehouse.MasterData_DW.DimDate
-- Generated by lineage_compiler. Review key grain before executing against live Fabric.

SELECT COUNT_BIG(*) AS row_count
FROM Enterprise_Lakehouse.MasterData_DW.DimDate;

SELECT [MapicsDate], [CalendarDate], [CalendarWeekFirstDate], [CalendarWeekLastDate], [CalendarMonthFirstDate], COUNT_BIG(*) AS duplicate_count
FROM Enterprise_Lakehouse.MasterData_DW.DimDate
GROUP BY [MapicsDate], [CalendarDate], [CalendarWeekFirstDate], [CalendarWeekLastDate], [CalendarMonthFirstDate]
HAVING COUNT_BIG(*) > 1;

SELECT COUNT_BIG(*) AS null_blank_key_rows
FROM Enterprise_Lakehouse.MasterData_DW.DimDate
WHERE [MapicsDate] IS NULL OR TRY_CAST([MapicsDate] AS VARCHAR(4000)) = '' OR [CalendarDate] IS NULL OR TRY_CAST([CalendarDate] AS VARCHAR(4000)) = '' OR [CalendarWeekFirstDate] IS NULL OR TRY_CAST([CalendarWeekFirstDate] AS VARCHAR(4000)) = '' OR [CalendarWeekLastDate] IS NULL OR TRY_CAST([CalendarWeekLastDate] AS VARCHAR(4000)) = '' OR [CalendarMonthFirstDate] IS NULL OR TRY_CAST([CalendarMonthFirstDate] AS VARCHAR(4000)) = '';

