-- DQ rerun template for Enterprise_Lakehouse.Wholesale_Codis_AFI.EXTORIT
-- Generated by lineage_compiler. Review key grain before executing against live Fabric.

SELECT COUNT_BIG(*) AS row_count
FROM Enterprise_Lakehouse.Wholesale_Codis_AFI.EXTORIT;

SELECT [IORD], [ISEQ], COUNT_BIG(*) AS duplicate_count
FROM Enterprise_Lakehouse.Wholesale_Codis_AFI.EXTORIT
GROUP BY [IORD], [ISEQ]
HAVING COUNT_BIG(*) > 1;

SELECT COUNT_BIG(*) AS null_blank_key_rows
FROM Enterprise_Lakehouse.Wholesale_Codis_AFI.EXTORIT
WHERE [IORD] IS NULL OR TRY_CAST([IORD] AS VARCHAR(4000)) = '' OR [ISEQ] IS NULL OR TRY_CAST([ISEQ] AS VARCHAR(4000)) = '';

