-- DQ rerun template for Enterprise_Lakehouse.SalesHistory_AFI_Enh.InvoiceHeader
-- Generated by lineage_compiler. Review key grain before executing against live Fabric.

SELECT COUNT_BIG(*) AS row_count
FROM Enterprise_Lakehouse.SalesHistory_AFI_Enh.InvoiceHeader;

SELECT [InvoiceNumber], COUNT_BIG(*) AS duplicate_count
FROM Enterprise_Lakehouse.SalesHistory_AFI_Enh.InvoiceHeader
GROUP BY [InvoiceNumber]
HAVING COUNT_BIG(*) > 1;

SELECT COUNT_BIG(*) AS null_blank_key_rows
FROM Enterprise_Lakehouse.SalesHistory_AFI_Enh.InvoiceHeader
WHERE [InvoiceNumber] IS NULL OR TRY_CAST([InvoiceNumber] AS VARCHAR(4000)) = '';

