-- DQ rerun template for Enterprise_Lakehouse.Customers.AccountMaster
-- Generated by lineage_compiler. Review key grain before executing against live Fabric.

SELECT COUNT_BIG(*) AS row_count
FROM Enterprise_Lakehouse.Customers.AccountMaster;

SELECT [cmaCustomerNumber], COUNT_BIG(*) AS duplicate_count
FROM Enterprise_Lakehouse.Customers.AccountMaster
GROUP BY [cmaCustomerNumber]
HAVING COUNT_BIG(*) > 1;

SELECT COUNT_BIG(*) AS null_blank_key_rows
FROM Enterprise_Lakehouse.Customers.AccountMaster
WHERE [cmaCustomerNumber] IS NULL OR TRY_CAST([cmaCustomerNumber] AS VARCHAR(4000)) = '';

