-- DQ rerun template for Enterprise_Lakehouse.Customers.ShippingLocations
-- Generated by lineage_compiler. Review key grain before executing against live Fabric.

SELECT COUNT_BIG(*) AS row_count
FROM Enterprise_Lakehouse.Customers.ShippingLocations;

SELECT [cslCustomerNumber], [cslShiptoNumber], COUNT_BIG(*) AS duplicate_count
FROM Enterprise_Lakehouse.Customers.ShippingLocations
GROUP BY [cslCustomerNumber], [cslShiptoNumber]
HAVING COUNT_BIG(*) > 1;

SELECT COUNT_BIG(*) AS null_blank_key_rows
FROM Enterprise_Lakehouse.Customers.ShippingLocations
WHERE [cslCustomerNumber] IS NULL OR TRY_CAST([cslCustomerNumber] AS VARCHAR(4000)) = '' OR [cslShiptoNumber] IS NULL OR TRY_CAST([cslShiptoNumber] AS VARCHAR(4000)) = '';

