-- DQ rerun template for Enterprise_Lakehouse.MasterData_DW.DimItemMaster
-- Generated by lineage_compiler. Review key grain before executing against live Fabric.

SELECT COUNT_BIG(*) AS row_count
FROM Enterprise_Lakehouse.MasterData_DW.DimItemMaster;

SELECT [ItemSKU], COUNT_BIG(*) AS duplicate_count
FROM Enterprise_Lakehouse.MasterData_DW.DimItemMaster
GROUP BY [ItemSKU]
HAVING COUNT_BIG(*) > 1;

SELECT COUNT_BIG(*) AS null_blank_key_rows
FROM Enterprise_Lakehouse.MasterData_DW.DimItemMaster
WHERE [ItemSKU] IS NULL OR TRY_CAST([ItemSKU] AS VARCHAR(4000)) = '';

