-- DQ rerun template for Enterprise_Lakehouse.ItemMaster_AFI.ITMEXT
-- Generated by lineage_compiler. Review key grain before executing against live Fabric.

SELECT COUNT_BIG(*) AS row_count
FROM Enterprise_Lakehouse.ItemMaster_AFI.ITMEXT;

SELECT [ITNBR], COUNT_BIG(*) AS duplicate_count
FROM Enterprise_Lakehouse.ItemMaster_AFI.ITMEXT
GROUP BY [ITNBR]
HAVING COUNT_BIG(*) > 1;

SELECT COUNT_BIG(*) AS null_blank_key_rows
FROM Enterprise_Lakehouse.ItemMaster_AFI.ITMEXT
WHERE [ITNBR] IS NULL OR TRY_CAST([ITNBR] AS VARCHAR(4000)) = '';

