-- DQ rerun template for Enterprise_Lakehouse.Wholesale_Codis_AFI.AAORDTYP
-- Generated by lineage_compiler. Review key grain before executing against live Fabric.

SELECT COUNT_BIG(*) AS row_count
FROM Enterprise_Lakehouse.Wholesale_Codis_AFI.AAORDTYP;

SELECT [OTDATE], COUNT_BIG(*) AS duplicate_count
FROM Enterprise_Lakehouse.Wholesale_Codis_AFI.AAORDTYP
GROUP BY [OTDATE]
HAVING COUNT_BIG(*) > 1;

SELECT COUNT_BIG(*) AS null_blank_key_rows
FROM Enterprise_Lakehouse.Wholesale_Codis_AFI.AAORDTYP
WHERE [OTDATE] IS NULL OR TRY_CAST([OTDATE] AS VARCHAR(4000)) = '';

