-- DQ rerun template for Enterprise_Lakehouse.ItemMaster_AFI.AITMCLS
-- Generated by lineage_compiler. Review key grain before executing against live Fabric.

SELECT COUNT_BIG(*) AS row_count
FROM Enterprise_Lakehouse.ItemMaster_AFI.AITMCLS;

-- Grain duplicate check skipped: no key_columns available.

-- Null/blank key check skipped: no key_columns available.

