-- DQ rerun template for Enterprise_Lakehouse.Wholesale_Codis_AFI.EXTORD
-- Generated by lineage_compiler. Review key grain before executing against live Fabric.

SELECT COUNT_BIG(*) AS row_count
FROM Enterprise_Lakehouse.Wholesale_Codis_AFI.EXTORD;

SELECT [WHSE], [CUSTNO], [HDATE], [ARDATE], COUNT_BIG(*) AS duplicate_count
FROM Enterprise_Lakehouse.Wholesale_Codis_AFI.EXTORD
GROUP BY [WHSE], [CUSTNO], [HDATE], [ARDATE]
HAVING COUNT_BIG(*) > 1;

SELECT COUNT_BIG(*) AS null_blank_key_rows
FROM Enterprise_Lakehouse.Wholesale_Codis_AFI.EXTORD
WHERE [WHSE] IS NULL OR TRY_CAST([WHSE] AS VARCHAR(4000)) = '' OR [CUSTNO] IS NULL OR TRY_CAST([CUSTNO] AS VARCHAR(4000)) = '' OR [HDATE] IS NULL OR TRY_CAST([HDATE] AS VARCHAR(4000)) = '' OR [ARDATE] IS NULL OR TRY_CAST([ARDATE] AS VARCHAR(4000)) = '';

