-- DQ rerun template for Enterprise_Lakehouse.CustomerOrders_AFI.WarehouseMaster
-- Generated by lineage_compiler. Review key grain before executing against live Fabric.

SELECT COUNT_BIG(*) AS row_count
FROM Enterprise_Lakehouse.CustomerOrders_AFI.WarehouseMaster;

SELECT [Warehouse], COUNT_BIG(*) AS duplicate_count
FROM Enterprise_Lakehouse.CustomerOrders_AFI.WarehouseMaster
GROUP BY [Warehouse]
HAVING COUNT_BIG(*) > 1;

SELECT COUNT_BIG(*) AS null_blank_key_rows
FROM Enterprise_Lakehouse.CustomerOrders_AFI.WarehouseMaster
WHERE [Warehouse] IS NULL OR TRY_CAST([Warehouse] AS VARCHAR(4000)) = '';

