-- ReferenceMaster_Enh_Wrk.v_CustomerAccount
CREATE   VIEW [ReferenceMaster_Enh_Wrk].[v_CustomerAccount] AS
WITH __bob_source AS (
SELECT
    CAST(TRIM(src.[cmaCustomerNumber]) AS VARCHAR(8000)) AS [cmaCustomerNumber],
    CAST(TRIM(src.[cmaPhone]) AS VARCHAR(8000)) AS [cmaPhone],
    CAST(TRIM(src.[cmaFaxtn]) AS VARCHAR(8000)) AS [cmaFaxtn],
    CAST(TRIM(src.[cmaContact]) AS VARCHAR(8000)) AS [cmaContact],
    CAST(TRIM(src.[cmaEmail]) AS VARCHAR(8000)) AS [cmaEmail],
    CAST(TRIM(src.[cmaPrimaryTerritory]) AS VARCHAR(8000)) AS [cmaPrimaryTerritory],
    CAST(TRIM(src.[cmaMinimumFreightCode]) AS VARCHAR(8000)) AS [cmaMinimumFreightCode],
    CAST(src.[cmaCreditLimitAmount] AS INT) AS [cmaCreditLimitAmount],
    CAST(TRIM(src.[cmaTermsCode]) AS VARCHAR(8000)) AS [cmaTermsCode],
    CAST(src.[cmaTermsDays] AS SMALLINT) AS [cmaTermsDays],
    CAST(src.[cmaCreditTerritoryID] AS SMALLINT) AS [cmaCreditTerritoryID],
    CAST(src.[cmaCancelBackOrders] AS SMALLINT) AS [cmaCancelBackOrders],
    CAST(src.[cmaAllowPartialShipment] AS SMALLINT) AS [cmaAllowPartialShipment],
    CAST(TRIM(src.[cmaCustomerClassCode]) AS VARCHAR(8000)) AS [cmaCustomerClassCode],
    CAST(TRIM(src.[cmaLanguageCode]) AS VARCHAR(8000)) AS [cmaLanguageCode],
    CAST(src.[cmaStatementCode] AS SMALLINT) AS [cmaStatementCode],
    CAST(TRIM(src.[cmaItemCrossReferenceCode]) AS VARCHAR(8000)) AS [cmaItemCrossReferenceCode],
    CAST(src.[cmaTerritoryChangeDate] AS DATETIME2(6)) AS [cmaTerritoryChangeDate],
    CAST(TRIM(src.[cmaCreditAuthorizationCode]) AS VARCHAR(8000)) AS [cmaCreditAuthorizationCode],
    CAST(TRIM(src.[cmaMemo]) AS VARCHAR(8000)) AS [cmaMemo],
    CAST(src.[cmaChgCustAr] AS BIT) AS [cmaChgCustAr],
    CAST(src.[cmaChgCust] AS BIT) AS [cmaChgCust],
    CAST(src.[cmaChgCustExt] AS BIT) AS [cmaChgCustExt],
    CAST(src.[cmaPercentAvailableCredit] AS DECIMAL(3,2)) AS [cmaPercentAvailableCredit],
    CAST(src.[cmaCommAudit] AS BIT) AS [cmaCommAudit],
    CAST(src.[cmaInheritBlocking] AS BIT) AS [cmaInheritBlocking],
    CAST(TRIM(src.[cmaCustomerName]) AS VARCHAR(8000)) AS [cmaCustomerName],
    CAST(TRIM(src.[usra]) AS VARCHAR(8000)) AS [usra],
    CAST(src.[dtea] AS DATETIME2(6)) AS [dtea],
    CAST(TRIM(src.[usrc]) AS VARCHAR(8000)) AS [usrc],
    CAST(src.[dtec] AS DATETIME2(6)) AS [dtec],
    CAST(TRIM(src.[acrec]) AS VARCHAR(8000)) AS [acrec],
    CAST(src.[cmaLastStatusChangeDate] AS DATETIME2(6)) AS [cmaLastStatusChangeDate],
    CAST(src.[cmaBillingAddressID] AS INT) AS [cmaBillingAddressID],
    CAST(TRIM(src.[cmaDBAName]) AS VARCHAR(8000)) AS [cmaDBAName],
    CAST(src.[cmaLateChargePercent] AS DECIMAL(5,4)) AS [cmaLateChargePercent],
    CAST(src.[cmaMinPreapprovalAmount] AS DECIMAL(12,2)) AS [cmaMinPreapprovalAmount],
    CAST(TRIM(src.[cmaCreditAddessCode]) AS VARCHAR(8000)) AS [cmaCreditAddessCode],
    CAST(TRIM(src.[cmaRFCTaxIdNumber]) AS VARCHAR(8000)) AS [cmaRFCTaxIdNumber],
    CAST(TRIM(src.[cmaDocumentationHold]) AS VARCHAR(8000)) AS [cmaDocumentationHold],
    CAST(TRIM(src.[cmaPARSByPurchaser]) AS VARCHAR(8000)) AS [cmaPARSByPurchaser],
    CAST(TRIM(src.[cma10DigitScheduleB]) AS VARCHAR(8000)) AS [cma10DigitScheduleB],
    CAST(TRIM(src.[cmaTypeOfInsurance]) AS VARCHAR(8000)) AS [cmaTypeOfInsurance],
    CAST(src.[cmaInsExpirationDate] AS DATETIME2(6)) AS [cmaInsExpirationDate],
    CAST(src.[cmaInsCoverageRequested] AS DECIMAL(10,2)) AS [cmaInsCoverageRequested],
    CAST(src.[cmaInsCoverageApproved] AS DECIMAL(10,2)) AS [cmaInsCoverageApproved],
    CAST(TRIM(src.[cmaInsuranceStatus]) AS VARCHAR(8000)) AS [cmaInsuranceStatus],
    CAST(TRIM(src.[cmaHomestoreFacingWhse]) AS VARCHAR(8000)) AS [cmaHomestoreFacingWhse],
    CAST(src.[cmaAppcd] AS INT) AS [cmaAppcd],
    CAST(src.[cmaDeductTerritoryID] AS DECIMAL(2,0)) AS [cmaDeductTerritoryID],
    CAST(TRIM(src.[cmaCurrencyCode]) AS VARCHAR(8000)) AS [cmaCurrencyCode],
    CAST(src.[cmaAllowAllowanceCredits] AS BIT) AS [cmaAllowAllowanceCredits],
    CAST(TRIM(src.[cmaCustomerChannelID]) AS VARCHAR(8000)) AS [cmaCustomerChannelID]
FROM [Enterprise_Lakehouse].[Customers].[AccountMaster] AS src
)
SELECT
    [cmaCustomerNumber] = src.[cmaCustomerNumber],
    [cmaPhone] = src.[cmaPhone],
    [cmaFaxtn] = src.[cmaFaxtn],
    [cmaContact] = src.[cmaContact],
    [cmaEmail] = src.[cmaEmail],
    [cmaPrimaryTerritory] = src.[cmaPrimaryTerritory],
    [cmaMinimumFreightCode] = src.[cmaMinimumFreightCode],
    [cmaCreditLimitAmount] = src.[cmaCreditLimitAmount],
    [cmaTermsCode] = src.[cmaTermsCode],
    [cmaTermsDays] = src.[cmaTermsDays],
    [cmaCreditTerritoryID] = src.[cmaCreditTerritoryID],
    [cmaCancelBackOrders] = src.[cmaCancelBackOrders],
    [cmaAllowPartialShipment] = src.[cmaAllowPartialShipment],
    [cmaCustomerClassCode] = src.[cmaCustomerClassCode],
    [cmaLanguageCode] = src.[cmaLanguageCode],
    [cmaStatementCode] = src.[cmaStatementCode],
    [cmaItemCrossReferenceCode] = src.[cmaItemCrossReferenceCode],
    [cmaTerritoryChangeDate] = src.[cmaTerritoryChangeDate],
    [cmaCreditAuthorizationCode] = src.[cmaCreditAuthorizationCode],
    [cmaMemo] = src.[cmaMemo],
    [cmaChgCustAr] = src.[cmaChgCustAr],
    [cmaChgCust] = src.[cmaChgCust],
    [cmaChgCustExt] = src.[cmaChgCustExt],
    [cmaPercentAvailableCredit] = src.[cmaPercentAvailableCredit],
    [cmaCommAudit] = src.[cmaCommAudit],
    [cmaInheritBlocking] = src.[cmaInheritBlocking],
    [cmaCustomerName] = src.[cmaCustomerName],
    [usra] = src.[usra],
    [dtea] = src.[dtea],
    [usrc] = src.[usrc],
    [dtec] = src.[dtec],
    [acrec] = src.[acrec],
    [cmaLastStatusChangeDate] = src.[cmaLastStatusChangeDate],
    [cmaBillingAddressID] = src.[cmaBillingAddressID],
    [cmaDBAName] = src.[cmaDBAName],
    [cmaLateChargePercent] = src.[cmaLateChargePercent],
    [cmaMinPreapprovalAmount] = src.[cmaMinPreapprovalAmount],
    [cmaCreditAddessCode] = src.[cmaCreditAddessCode],
    [cmaRFCTaxIdNumber] = src.[cmaRFCTaxIdNumber],
    [cmaDocumentationHold] = src.[cmaDocumentationHold],
    [cmaPARSByPurchaser] = src.[cmaPARSByPurchaser],
    [cma10DigitScheduleB] = src.[cma10DigitScheduleB],
    [cmaTypeOfInsurance] = src.[cmaTypeOfInsurance],
    [cmaInsExpirationDate] = src.[cmaInsExpirationDate],
    [cmaInsCoverageRequested] = src.[cmaInsCoverageRequested],
    [cmaInsCoverageApproved] = src.[cmaInsCoverageApproved],
    [cmaInsuranceStatus] = src.[cmaInsuranceStatus],
    [cmaHomestoreFacingWhse] = src.[cmaHomestoreFacingWhse],
    [cmaAppcd] = src.[cmaAppcd],
    [cmaDeductTerritoryID] = src.[cmaDeductTerritoryID],
    [cmaCurrencyCode] = src.[cmaCurrencyCode],
    [cmaAllowAllowanceCredits] = src.[cmaAllowAllowanceCredits],
    [cmaCustomerChannelID] = src.[cmaCustomerChannelID],
    [LoadDT] = CAST(SYSUTCDATETIME() AS datetime2(6))
FROM __bob_source AS src;
