-- ReferenceMaster_Enh_Wrk.v_CustomerShippingLocation
CREATE   VIEW [ReferenceMaster_Enh_Wrk].[v_CustomerShippingLocation] AS
WITH __bob_source AS (
SELECT
    CAST(src.[commAudit] AS BIT) AS [commAudit],
    CAST(src.[commAudit2] AS BIT) AS [commAudit2],
    CAST(TRIM(src.[cslCustomerNumber]) AS VARCHAR(8000)) AS [cslCustomerNumber],
    CAST(TRIM(src.[cslShiptoNumber]) AS VARCHAR(8000)) AS [cslShiptoNumber],
    CAST(src.[cslMapicsSequenceNumber] AS SMALLINT) AS [cslMapicsSequenceNumber],
    CAST(TRIM(src.[cslName]) AS VARCHAR(8000)) AS [cslName],
    CAST(TRIM(src.[csmShpa1]) AS VARCHAR(8000)) AS [csmShpa1],
    CAST(TRIM(src.[csmShpa2]) AS VARCHAR(8000)) AS [csmShpa2],
    CAST(TRIM(src.[csmShpa3]) AS VARCHAR(8000)) AS [csmShpa3],
    CAST(TRIM(src.[csmShpzp]) AS VARCHAR(8000)) AS [csmShpzp],
    CAST(TRIM(src.[csmShpst]) AS VARCHAR(8000)) AS [csmShpst],
    CAST(TRIM(src.[csmShpco]) AS VARCHAR(8000)) AS [csmShpco],
    CAST(TRIM(src.[csmPhone]) AS VARCHAR(8000)) AS [csmPhone],
    CAST(TRIM(src.[csmFaxTn]) AS VARCHAR(8000)) AS [csmFaxTn],
    CAST(TRIM(src.[cslTaxExempt]) AS VARCHAR(8000)) AS [cslTaxExempt],
    CAST(TRIM(src.[csmWebsite]) AS VARCHAR(8000)) AS [csmWebsite],
    CAST(TRIM(src.[csmEmail]) AS VARCHAR(8000)) AS [csmEmail],
    CAST(TRIM(src.[cslCommissionCode]) AS VARCHAR(8000)) AS [cslCommissionCode],
    CAST(TRIM(src.[cslFreightCode]) AS VARCHAR(8000)) AS [cslFreightCode],
    CAST(TRIM(src.[cslPriceCode]) AS VARCHAR(8000)) AS [cslPriceCode],
    CAST(TRIM(src.[cslDiscountCode]) AS VARCHAR(8000)) AS [cslDiscountCode],
    CAST(src.[cslCommissionSplit] AS DECIMAL(7,4)) AS [cslCommissionSplit],
    CAST(TRIM(src.[cslDefaultWarehouse]) AS VARCHAR(8000)) AS [cslDefaultWarehouse],
    CAST(TRIM(src.[cslShippingTerritory]) AS VARCHAR(8000)) AS [cslShippingTerritory],
    CAST(TRIM(src.[cslBusinessType]) AS VARCHAR(8000)) AS [cslBusinessType],
    CAST(TRIM(src.[cslShipType]) AS VARCHAR(8000)) AS [cslShipType],
    CAST(TRIM(src.[cslTranscomPrimaryID]) AS VARCHAR(8000)) AS [cslTranscomPrimaryID],
    CAST(TRIM(src.[csmContact]) AS VARCHAR(8000)) AS [csmContact],
    CAST(TRIM(src.[cslComment1]) AS VARCHAR(8000)) AS [cslComment1],
    CAST(TRIM(src.[cslComment2]) AS VARCHAR(8000)) AS [cslComment2],
    CAST(src.[cslTerritoryEffectivityDate] AS DATETIME2(6)) AS [cslTerritoryEffectivityDate],
    CAST(TRIM(src.[cslCrmID]) AS VARCHAR(8000)) AS [cslCrmID],
    CAST(TRIM(src.[csmCsPhone]) AS VARCHAR(8000)) AS [csmCsPhone],
    CAST(TRIM(src.[csmcsFax]) AS VARCHAR(8000)) AS [csmcsFax],
    CAST(TRIM(src.[csmcsContact]) AS VARCHAR(8000)) AS [csmcsContact],
    CAST(TRIM(src.[csmcsEmail]) AS VARCHAR(8000)) AS [csmcsEmail],
    CAST(TRIM(src.[cslMemo]) AS VARCHAR(8000)) AS [cslMemo],
    CAST(TRIM(src.[csmMsa_Fips]) AS VARCHAR(8000)) AS [csmMsa_Fips],
    CAST(src.[csmRMCityNumber] AS INT) AS [csmRMCityNumber],
    CAST(TRIM(src.[cslTranscomAlternateID]) AS VARCHAR(8000)) AS [cslTranscomAlternateID],
    CAST(TRIM(src.[csmDirections]) AS VARCHAR(8000)) AS [csmDirections],
    CAST(TRIM(src.[csmCrossStreet]) AS VARCHAR(8000)) AS [csmCrossStreet],
    CAST(src.[csmChgAddr] AS BIT) AS [csmChgAddr],
    CAST(src.[csmChgShip] AS BIT) AS [csmChgShip],
    CAST(src.[csmChgShipExt] AS BIT) AS [csmChgShipExt],
    CAST(src.[csmChgCust] AS BIT) AS [csmChgCust],
    CAST(TRIM(src.[usra]) AS VARCHAR(8000)) AS [usra],
    CAST(src.[dtea] AS DATETIME2(6)) AS [dtea],
    CAST(TRIM(src.[usrc]) AS VARCHAR(8000)) AS [usrc],
    CAST(src.[dtec] AS DATETIME2(6)) AS [dtec],
    CAST(TRIM(src.[acrec]) AS VARCHAR(8000)) AS [acrec],
    CAST(TRIM(src.[csmCounty]) AS VARCHAR(8000)) AS [csmCounty],
    CAST(src.[cslBlockRepOrderEntry] AS BIT) AS [cslBlockRepOrderEntry],
    CAST(src.[cslCustomerSegment] AS SMALLINT) AS [cslCustomerSegment],
    CAST(src.[cslLastStatusChangeDate] AS DATETIME2(6)) AS [cslLastStatusChangeDate],
    CAST(src.[cslBuyerAddressID] AS INT) AS [cslBuyerAddressID],
    CAST(src.[cslPartyLocationID] AS INT) AS [cslPartyLocationID],
    CAST(src.[cslRouteAddressID] AS INT) AS [cslRouteAddressID],
    CAST(TRIM(src.[cslDefaultOrderType1]) AS VARCHAR(8000)) AS [cslDefaultOrderType1],
    CAST(TRIM(src.[cslDefaultOrderType2]) AS VARCHAR(8000)) AS [cslDefaultOrderType2],
    CAST(TRIM(src.[cslDefaultOrderType3]) AS VARCHAR(8000)) AS [cslDefaultOrderType3],
    CAST(TRIM(src.[cslDefaultOrderType4]) AS VARCHAR(8000)) AS [cslDefaultOrderType4],
    CAST(src.[csmShled] AS SMALLINT) AS [csmShled],
    CAST(src.[csmAppcd] AS INT) AS [csmAppcd],
    CAST(TRIM(src.[cslAllowFax]) AS VARCHAR(8000)) AS [cslAllowFax],
    CAST(TRIM(src.[cslDirectConsumer]) AS VARCHAR(8000)) AS [cslDirectConsumer],
    CAST(TRIM(src.[cslDeliveryUnitOfMeasure]) AS VARCHAR(8000)) AS [cslDeliveryUnitOfMeasure],
    CAST(src.[cslDeliveryUnitOfMeasureFence] AS DECIMAL(7,2)) AS [cslDeliveryUnitOfMeasureFence],
    CAST(TRIM(src.[cslExportsLCLConsolidationFlag]) AS VARCHAR(8000)) AS [cslExportsLCLConsolidationFlag],
    CAST(TRIM(src.[cslExportsDocumentCountry]) AS VARCHAR(8000)) AS [cslExportsDocumentCountry],
    CAST(TRIM(src.[cslExportsProductOnPallets]) AS VARCHAR(8000)) AS [cslExportsProductOnPallets],
    CAST(TRIM(src.[cslExportsAppointmentsRequired]) AS VARCHAR(8000)) AS [cslExportsAppointmentsRequired],
    CAST(src.[cslHasDock] AS BIT) AS [cslHasDock],
    CAST(TRIM(src.[cslHasDockUserDate]) AS VARCHAR(8000)) AS [cslHasDockUserDate],
    CAST(TRIM(src.[cslExpressShippingMethod]) AS VARCHAR(8000)) AS [cslExpressShippingMethod],
    CAST(TRIM(src.[cslDirectIncludeShipto]) AS VARCHAR(8000)) AS [cslDirectIncludeShipto],
    CAST(src.[cslExpressHandlingCharge] AS DECIMAL(4,3)) AS [cslExpressHandlingCharge],
    CAST(src.[cslExpressMinimum] AS DECIMAL(10,2)) AS [cslExpressMinimum],
    CAST(src.[cslExpressMaximum] AS DECIMAL(10,2)) AS [cslExpressMaximum],
    CAST(TRIM(src.[cslDefaultLanguage]) AS VARCHAR(8000)) AS [cslDefaultLanguage],
    CAST(TRIM(src.[cslExpressServiceContractNumber]) AS VARCHAR(8000)) AS [cslExpressServiceContractNumber],
    CAST(TRIM(src.[cslUseNegotiatedFreightRate]) AS VARCHAR(8000)) AS [cslUseNegotiatedFreightRate],
    CAST(TRIM(src.[cslUseStandardFreightRate]) AS VARCHAR(8000)) AS [cslUseStandardFreightRate],
    CAST(TRIM(src.[cslDoNotRepriceOrders]) AS VARCHAR(8000)) AS [cslDoNotRepriceOrders],
    CAST(TRIM(src.[cslPricingUseOfflineFiles]) AS VARCHAR(8000)) AS [cslPricingUseOfflineFiles],
    CAST(src.[cslReturnAddressID] AS INT) AS [cslReturnAddressID],
    CAST(TRIM(src.[cslReturnAddressName]) AS VARCHAR(8000)) AS [cslReturnAddressName]
FROM [Enterprise_Lakehouse].[Customers].[ShippingLocations] AS src
)
SELECT
    [commAudit] = src.[commAudit],
    [commAudit2] = src.[commAudit2],
    [cslCustomerNumber] = src.[cslCustomerNumber],
    [cslShiptoNumber] = src.[cslShiptoNumber],
    [cslMapicsSequenceNumber] = src.[cslMapicsSequenceNumber],
    [cslName] = src.[cslName],
    [csmShpa1] = src.[csmShpa1],
    [csmShpa2] = src.[csmShpa2],
    [csmShpa3] = src.[csmShpa3],
    [csmShpzp] = src.[csmShpzp],
    [csmShpst] = src.[csmShpst],
    [csmShpco] = src.[csmShpco],
    [csmPhone] = src.[csmPhone],
    [csmFaxTn] = src.[csmFaxTn],
    [cslTaxExempt] = src.[cslTaxExempt],
    [csmWebsite] = src.[csmWebsite],
    [csmEmail] = src.[csmEmail],
    [cslCommissionCode] = src.[cslCommissionCode],
    [cslFreightCode] = src.[cslFreightCode],
    [cslPriceCode] = src.[cslPriceCode],
    [cslDiscountCode] = src.[cslDiscountCode],
    [cslCommissionSplit] = src.[cslCommissionSplit],
    [cslDefaultWarehouse] = src.[cslDefaultWarehouse],
    [cslShippingTerritory] = src.[cslShippingTerritory],
    [cslBusinessType] = src.[cslBusinessType],
    [cslShipType] = src.[cslShipType],
    [cslTranscomPrimaryID] = src.[cslTranscomPrimaryID],
    [csmContact] = src.[csmContact],
    [cslComment1] = src.[cslComment1],
    [cslComment2] = src.[cslComment2],
    [cslTerritoryEffectivityDate] = src.[cslTerritoryEffectivityDate],
    [cslCrmID] = src.[cslCrmID],
    [csmCsPhone] = src.[csmCsPhone],
    [csmcsFax] = src.[csmcsFax],
    [csmcsContact] = src.[csmcsContact],
    [csmcsEmail] = src.[csmcsEmail],
    [cslMemo] = src.[cslMemo],
    [csmMsa_Fips] = src.[csmMsa_Fips],
    [csmRMCityNumber] = src.[csmRMCityNumber],
    [cslTranscomAlternateID] = src.[cslTranscomAlternateID],
    [csmDirections] = src.[csmDirections],
    [csmCrossStreet] = src.[csmCrossStreet],
    [csmChgAddr] = src.[csmChgAddr],
    [csmChgShip] = src.[csmChgShip],
    [csmChgShipExt] = src.[csmChgShipExt],
    [csmChgCust] = src.[csmChgCust],
    [usra] = src.[usra],
    [dtea] = src.[dtea],
    [usrc] = src.[usrc],
    [dtec] = src.[dtec],
    [acrec] = src.[acrec],
    [csmCounty] = src.[csmCounty],
    [cslBlockRepOrderEntry] = src.[cslBlockRepOrderEntry],
    [cslCustomerSegment] = src.[cslCustomerSegment],
    [cslLastStatusChangeDate] = src.[cslLastStatusChangeDate],
    [cslBuyerAddressID] = src.[cslBuyerAddressID],
    [cslPartyLocationID] = src.[cslPartyLocationID],
    [cslRouteAddressID] = src.[cslRouteAddressID],
    [cslDefaultOrderType1] = src.[cslDefaultOrderType1],
    [cslDefaultOrderType2] = src.[cslDefaultOrderType2],
    [cslDefaultOrderType3] = src.[cslDefaultOrderType3],
    [cslDefaultOrderType4] = src.[cslDefaultOrderType4],
    [csmShled] = src.[csmShled],
    [csmAppcd] = src.[csmAppcd],
    [cslAllowFax] = src.[cslAllowFax],
    [cslDirectConsumer] = src.[cslDirectConsumer],
    [cslDeliveryUnitOfMeasure] = src.[cslDeliveryUnitOfMeasure],
    [cslDeliveryUnitOfMeasureFence] = src.[cslDeliveryUnitOfMeasureFence],
    [cslExportsLCLConsolidationFlag] = src.[cslExportsLCLConsolidationFlag],
    [cslExportsDocumentCountry] = src.[cslExportsDocumentCountry],
    [cslExportsProductOnPallets] = src.[cslExportsProductOnPallets],
    [cslExportsAppointmentsRequired] = src.[cslExportsAppointmentsRequired],
    [cslHasDock] = src.[cslHasDock],
    [cslHasDockUserDate] = src.[cslHasDockUserDate],
    [cslExpressShippingMethod] = src.[cslExpressShippingMethod],
    [cslDirectIncludeShipto] = src.[cslDirectIncludeShipto],
    [cslExpressHandlingCharge] = src.[cslExpressHandlingCharge],
    [cslExpressMinimum] = src.[cslExpressMinimum],
    [cslExpressMaximum] = src.[cslExpressMaximum],
    [cslDefaultLanguage] = src.[cslDefaultLanguage],
    [cslExpressServiceContractNumber] = src.[cslExpressServiceContractNumber],
    [cslUseNegotiatedFreightRate] = src.[cslUseNegotiatedFreightRate],
    [cslUseStandardFreightRate] = src.[cslUseStandardFreightRate],
    [cslDoNotRepriceOrders] = src.[cslDoNotRepriceOrders],
    [cslPricingUseOfflineFiles] = src.[cslPricingUseOfflineFiles],
    [cslReturnAddressID] = src.[cslReturnAddressID],
    [cslReturnAddressName] = src.[cslReturnAddressName],
    [LoadDT] = CAST(SYSUTCDATETIME() AS datetime2(6))
FROM __bob_source AS src;
