-- Generated from live Fabric metadata: Enterprise_Lakehouse
CREATE TABLE [SalesHistory_AFI_Enh].[InvoiceHeader] (
    [CustomerNumber] varchar(8000) NOT NULL,
    [ShiptoNumber] varchar(8000) NOT NULL,
    [InvoiceNumber] decimal(9,0) NOT NULL,
    [OrderNumber] varchar(8000) NOT NULL,
    [PurchaseOrder] varchar(8000) NOT NULL,
    [Warehouse] varchar(8000) NOT NULL,
    [InvoiceAmount] decimal(9,2) NOT NULL,
    [ShiptoName] varchar(8000) NOT NULL,
    [ShiptoAddress1] varchar(8000) NOT NULL,
    [ShiptoAddress2] varchar(8000) NULL,
    [ShiptoCity] varchar(8000) NOT NULL,
    [ShiptoState] varchar(8000) NOT NULL,
    [ShiptoZipCode] varchar(8000) NOT NULL,
    [ShiptoSalesman] varchar(8000) NOT NULL,
    [PostingMonth] varchar(8000) NOT NULL,
    [OrderArrivalCode] varchar(8000) NOT NULL,
    [AdvertisingFlag] varchar(8000) NOT NULL,
    [OrderType] varchar(8000) NOT NULL,
    [RequestDate] date NULL,
    [OrderDate] date NULL,
    [InvoiceDate] date NOT NULL,
    [LeadTime] int NOT NULL,
    [TripNumber] decimal(7,0) NOT NULL,
    [TaxAmount] decimal(13,2) NOT NULL,
    [DropNumber] decimal(2,0) NOT NULL,
    [OrderTypePrimary] varchar(8000) NOT NULL,
    [OrderTypeSecondary] varchar(8000) NOT NULL,
    [OrderTypeUsrDefine3] varchar(8000) NOT NULL,
    [OrderTypeUsrDefine4] varchar(8000) NOT NULL,
    [ShipInstructions] varchar(8000) NULL,
    [ShipWeight] decimal(10,2) NULL,
    [TermsDiscount] decimal(5,3) NULL,
    [TripCreatedDate] date NULL,
    [CreditCode] varchar(8000) NULL,
    [CurrencyCode] varchar(8000) NULL,
    [PromotionNumber] varchar(8000) NULL,
    [CreditApprovalNBR] varchar(8000) NULL,
    [SoldtoName] varchar(8000) NULL,
    [ShiptoCountryName] varchar(8000) NULL,
    [Sequence] decimal(2,0) NULL
);
