-- Physical final table contract: [SupplyChain_Processing_Warehouse].[InventoryHistory_Enh].[AtpWeekEnding]
-- Loaded by ETL_Framework from [SupplyChain_Processing_Warehouse].[InventoryHistory_Enh_Wrk].[v_AtpWeekEnding].
-- Business/source view SQL is documented in ../InventoryHistory_Enh_Wrk/v_AtpWeekEnding.sql.
