-- Physical final table contract: [SupplyChain_Processing_Warehouse].[InventoryHistory_Enh].[AwdHelper]
-- Loaded by ETL_Framework from [SupplyChain_Processing_Warehouse].[InventoryHistory_Enh_Wrk].[v_AwdHelper].
-- Business/source view SQL is documented in ../InventoryHistory_Enh_Wrk/v_AwdHelper.sql.
