-- Physical final table contract: [SupplyChain_Processing_Warehouse].[InventoryHistory_Enh].[ForecastSnapshotWeekly]
-- Loaded by ETL_Framework from [SupplyChain_Processing_Warehouse].[InventoryHistory_Enh_Wrk].[v_ForecastSnapshotWeekly].
-- Business/source view SQL is documented in ../InventoryHistory_Enh_Wrk/v_ForecastSnapshotWeekly.sql.
