-- Physical final table contract: [SupplyChain_Processing_Warehouse].[InventoryHistory_Enh].[ItemBalanceHistorical_WithInTransit]
-- Loaded by ETL_Framework from [SupplyChain_Processing_Warehouse].[InventoryHistory_Enh_Wrk].[v_ItemBalanceHistorical_WithInTransit].
-- Business/source view SQL is documented in ../InventoryHistory_Enh_Wrk/v_ItemBalanceHistorical_WithInTransit.sql.
