-- Generated from live Fabric metadata: SupplyChain_Processing_Warehouse
CREATE TABLE [OpenOrderHistory_Enh].[OpenOrderLineLevel] (
    [OrderID] varchar(8000) NULL,
    [ItemSequenceNum] int NULL,
    [Customer] varchar(8000) NULL,
    [ShipToCode] varchar(8000) NULL,
    [AccountShipTo] varchar(8000) NULL,
    [ItemSKU] varchar(8000) NULL,
    [WarehouseCode] varchar(8000) NULL,
    [QtyOpenOrder] int NULL,
    [QtyBackorder] int NULL,
    [AmtOpenOrder] decimal(13,2) NULL,
    [AmtBackorder] decimal(13,2) NULL,
    [OrderTaken] date NULL,
    [OriginalPromise] date NULL,
    [CurrentPromise] date NULL,
    [OriginalRequest] date NULL,
    [CurrentRequest] date NULL,
    [CurrentLoad] date NULL,
    [OrderArrivalCode] varchar(8000) NULL,
    [AllocationFlagCode] varchar(200) NULL,
    [LoadDateChangesNum] int NULL,
    [LeadTimeDaysNum] int NULL,
    [ShippingInstructionsName] varchar(8000) NULL,
    [CustomerSKUName] varchar(8000) NULL,
    [AmtOrderFreight] decimal(12,2) NULL,
    [PastDueFlagCode] varchar(10) NOT NULL,
    [LoadDT] datetime2(6) NULL
);
