-- Physical final table contract: [SupplyChain_Gold_Warehouse].[InventoryHealth_DW].[SupplyPlanOutageClassHelper]
-- Loaded by ETL_Framework from [SupplyChain_Gold_Warehouse].[InventoryHealth_DW_Wrk].[v_SupplyPlanOutageClassHelper].
-- Business/source view SQL is documented in ../InventoryHealth_DW_Wrk/v_SupplyPlanOutageClassHelper.sql.
