-- SupplyChain_Processing_Warehouse.ReferenceMaster_Enh_Wrk.v_OrderType
CREATE   VIEW [ReferenceMaster_Enh_Wrk].[v_OrderType] AS
SELECT
    CAST(TRIM(src.[OTCODE]) AS VARCHAR(8000)) AS [OTCODE],
    CAST(TRIM(src.[OTDES1]) AS VARCHAR(8000)) AS [OTDES1],
    CAST(TRIM(src.[OTDES2]) AS VARCHAR(8000)) AS [OTDES2],
    CAST(TRIM(src.[OTUSER]) AS VARCHAR(8000)) AS [OTUSER],
    CAST(src.[OTDATE] AS DECIMAL(8,0)) AS [OTDATE],
    CAST(TRIM(src.[OORDCL]) AS VARCHAR(8000)) AS [OORDCL],
    CAST(TRIM(src.[OROUTE]) AS VARCHAR(8000)) AS [OROUTE],
    CAST(TRIM(src.[OOTCAT]) AS VARCHAR(8000)) AS [OOTCAT],
    CAST(TRIM(src.[OADCHG]) AS VARCHAR(8000)) AS [OADCHG],
    CAST(TRIM(src.[OARFLG]) AS VARCHAR(8000)) AS [OARFLG],
    CAST(TRIM(src.[OWNEXP]) AS VARCHAR(8000)) AS [OWNEXP],
    CAST(TRIM(src.[OMINEXC]) AS VARCHAR(8000)) AS [OMINEXC],
    CAST(TRIM(src.[OREQMNT]) AS VARCHAR(8000)) AS [OREQMNT],
    CAST(TRIM(src.[OFDESCH]) AS VARCHAR(8000)) AS [OFDESCH],
    CAST(TRIM(src.[OFDRIMS]) AS VARCHAR(8000)) AS [OFDRIMS],
    CAST(TRIM(src.[OTRPTYP]) AS VARCHAR(8000)) AS [OTRPTYP],
    CAST(TRIM(src.[OZNLTIM]) AS VARCHAR(8000)) AS [OZNLTIM],
    CAST(TRIM(src.[OSPECHND]) AS VARCHAR(8000)) AS [OSPECHND],
    CAST(TRIM(src.[OAUTORSCH]) AS VARCHAR(8000)) AS [OAUTORSCH],
    CAST(TRIM(src.[OUSRDFN]) AS VARCHAR(8000)) AS [OUSRDFN],
    CAST(SYSUTCDATETIME() AS datetime2(6)) AS [LoadDT]
FROM [Enterprise_Lakehouse].[Wholesale_Codis_AFI].[AAORDTYP] AS src;
