-- Source: SupplyChain_Warehouse.queryinsights.exec_sessions_history
-- Generated from INFORMATION_SCHEMA.COLUMNS.
-- This is a logical schema snapshot; review Fabric physical options before execution.
CREATE TABLE [queryinsights].[exec_sessions_history] (
    [session_id] int NULL,
    [connection_id] uniqueidentifier NULL,
    [session_start_time] datetime2(6) NULL,
    [session_end_time] datetime2(6) NULL,
    [program_name] varchar(256) NULL,
    [login_name] varchar(256) NULL,
    [status] varchar(100) NULL,
    [context_info] varchar(128) NULL,
    [total_query_elapsed_time_ms] bigint NULL,
    [last_request_start_time] datetime2(6) NULL,
    [last_request_end_time] datetime2(6) NULL,
    [is_user_process] bit NULL,
    [prev_error] int NULL,
    [group_id] bigint NULL,
    [database_id] int NULL,
    [authenticating_database_id] int NULL,
    [open_transaction_count] bigint NULL,
    [text_size] int NULL,
    [language] varchar(256) NULL,
    [date_format] varchar(20) NULL,
    [date_first] int NULL,
    [quoted_identifier] bit NULL,
    [arithabort] bit NULL,
    [ansi_null_dflt_on] bit NULL,
    [ansi_defaults] bit NULL,
    [ansi_warnings] bit NULL,
    [ansi_padding] bit NULL,
    [ansi_nulls] bit NULL,
    [concat_null_yields_null] bit NULL,
    [transaction_isolation_level] int NULL,
    [lock_timeout] bigint NULL,
    [deadlock_priority] int NULL,
    [original_security_id] varchar(200) NULL,
    [database_name] varchar(200) NULL
);
