CREATE VIEW [Meta].[vw_RegistryCompat] AS

SELECT
    legacy_sp_name AS sp_name,
    legacy_view_name AS view_name,
    legacy_target_schema AS target_schema,
    legacy_target_table AS target_table,
    legacy_layer AS layer,
    load_type,
    frequency,
    scheduled_hour,
    CAST(NULL AS INT) AS execution_order,
    CAST(NULL AS VARCHAR(128)) AS parallel_group,
    depends_on,
    source_objects,
    watermark_column,
    primary_key,
    is_active,
    last_load_date,
    last_watermark_value,
    next_run_time,
    rows_loaded,
    project,
    date_key,
    date_range_days,
    cron_expression,
    canonical_layer,
    access_mode,
    physical_item,
    physical_schema,
    physical_object,
    approval_status,
    edw_exit_status
FROM Meta.AssetRegistry
