-- Target database: SupplyChain_Processing_Warehouse
-- Mart: inventory_health
-- Wave order: Silver W01 inventory source transformations
-- Generated by 03_operations/tools/generate_wave_sps.py
CREATE OR ALTER PROCEDURE [dbo].[Usp_Refresh_InventoryHealth_Silver_W01]
AS
BEGIN
    SET NOCOUNT ON;

    EXEC [ETL_Framework].[DW_Developer].[usp_RefreshCuratedTableFromView]
        'SupplyChain_Processing_Warehouse', 'InventoryHistory_Enh', 'InventorySnapshotWeekly';

    EXEC [ETL_Framework].[DW_Developer].[usp_RefreshCuratedTableFromView]
        'SupplyChain_Processing_Warehouse', 'InventoryHistory_Enh', 'AtpWeekEnding';
END;
