-- Target database: SupplyChain_Processing_Warehouse
-- Mart: inventory_health
-- Wave order: Silver W03 dependent helper tables
-- Generated by 03_operations/tools/generate_wave_sps.py
CREATE OR ALTER PROCEDURE [dbo].[Usp_Refresh_InventoryHealth_Silver_W03]
AS
BEGIN
    SET NOCOUNT ON;

    EXEC [ETL_Framework].[DW_Developer].[usp_RefreshCuratedTableFromView]
        'SupplyChain_Processing_Warehouse', 'InventoryHistory_Enh', 'AFIStatusSnapshotWeekly';

    EXEC [ETL_Framework].[DW_Developer].[usp_RefreshCuratedTableFromView]
        'SupplyChain_Processing_Warehouse', 'InventoryHistory_Enh', 'AwdHelper';

    EXEC [ETL_Framework].[DW_Developer].[usp_RefreshCuratedTableFromView]
        'SupplyChain_Processing_Warehouse', 'InventoryHistory_Enh', 'LastInvoiceWeekly';

    EXEC [ETL_Framework].[DW_Developer].[usp_RefreshCuratedTableFromView]
        'SupplyChain_Processing_Warehouse', 'InventoryHistory_Enh', 'Cogs52WWeekly';
END;
