-- Target database: SupplyChain_Processing_Warehouse
-- Mart: inventory_health
-- Wave order: Silver W02 derived source tables
-- Generated by 03_operations/tools/generate_wave_sps.py
CREATE OR ALTER PROCEDURE [dbo].[Usp_Refresh_InventoryHealth_Silver_W02]
AS
BEGIN
    SET NOCOUNT ON;

    DECLARE @PurchaseOrderWindowStart date = DATEADD(day, -30, CAST(GETDATE() AS date));
    DECLARE @PurchaseOrderSourceRows bigint;
    DECLARE @PurchaseOrderDuplicateGroups bigint;
    DECLARE @PurchaseOrderGuardMessage varchar(2047);

    SELECT @PurchaseOrderSourceRows = COUNT_BIG(*)
    FROM [InventoryHistory_Enh_Wrk].[v_PurchaseOrderSnapshotHistorical]
    WHERE SnapshotDate >= @PurchaseOrderWindowStart;

    IF @PurchaseOrderSourceRows = 0
    BEGIN
        SET @PurchaseOrderGuardMessage =
            'PurchaseOrderSnapshotHistorical DateRange guard failed: target was not changed; '
            + 'date key=SnapshotDate; window start=' + CONVERT(varchar(10), @PurchaseOrderWindowStart, 23)
            + '; source rows=0; duplicate groups=not evaluated.';
        THROW 51000, @PurchaseOrderGuardMessage, 1;
    END;

    SELECT @PurchaseOrderDuplicateGroups = COUNT_BIG(*)
    FROM
    (
        SELECT SnapshotDate, ItemSku, WarehouseCode, VendorNumber, StatusCode, DueDate, UnitCost
        FROM [InventoryHistory_Enh_Wrk].[v_PurchaseOrderSnapshotHistorical]
        WHERE SnapshotDate >= @PurchaseOrderWindowStart
        GROUP BY SnapshotDate, ItemSku, WarehouseCode, VendorNumber, StatusCode, DueDate, UnitCost
        HAVING COUNT_BIG(*) > 1
    ) AS DuplicatePurchaseOrderKeys;

    IF @PurchaseOrderDuplicateGroups > 0
    BEGIN
        SET @PurchaseOrderGuardMessage =
            'PurchaseOrderSnapshotHistorical DateRange guard failed: target was not changed; '
            + 'date key=SnapshotDate; window start=' + CONVERT(varchar(10), @PurchaseOrderWindowStart, 23)
            + '; source rows=' + CONVERT(varchar(30), @PurchaseOrderSourceRows)
            + '; duplicate groups=' + CONVERT(varchar(30), @PurchaseOrderDuplicateGroups) + '.';
        THROW 51001, @PurchaseOrderGuardMessage, 1;
    END;

    EXEC [ETL_Framework].[DW_Developer].[usp_UpdateCuratedTableFromView_DateRange]
        'SupplyChain_Processing_Warehouse',
        'InventoryHistory_Enh',
        'PurchaseOrderSnapshotHistorical',
        'SnapshotDate',
        'SnapshotDate',
        -30;

    EXEC [ETL_Framework].[DW_Developer].[usp_RefreshCuratedTableFromView]
        'SupplyChain_Processing_Warehouse', 'InventoryHistory_Enh', 'ManufacturingOrderSnapshotDaily';

    EXEC [ETL_Framework].[DW_Developer].[usp_RefreshCuratedTableFromView]
        'SupplyChain_Processing_Warehouse', 'InventoryHistory_Enh', 'HoldingTransferSnapshotDaily';

    EXEC [ETL_Framework].[DW_Developer].[usp_UpdateCuratedTableFromView_DateRange]
        'SupplyChain_Processing_Warehouse', 'InventoryHistory_Enh', 'ForecastSnapshotWeekly', 'SnapshotDate', 'SnapshotDate', -30;

    EXEC [ETL_Framework].[DW_Developer].[usp_RefreshCuratedTableFromView]
        'SupplyChain_Processing_Warehouse', 'InventoryHistory_Enh', 'SupplyPlanDetail';

    EXEC [ETL_Framework].[DW_Developer].[usp_RefreshCuratedTableFromView]
        'SupplyChain_Processing_Warehouse', 'InventoryHistory_Enh', 'ItemBalanceHistorical_WithInTransit';

    EXEC [ETL_Framework].[DW_Developer].[usp_RefreshCuratedTableFromView]
        'SupplyChain_Processing_Warehouse', 'InventoryHistory_Enh', 'SafetyStockHelper';

    EXEC [ETL_Framework].[DW_Developer].[usp_RefreshCuratedTableFromView]
        'SupplyChain_Processing_Warehouse', 'SalesHistory_Enh', 'InvoiceDetailLineLevel';
END;
