-- Enterprise_Lakehouse.Wholesale_ProductSourcing_AFI.PoDetail
-- Layer: Bronze/source shortcut reference for mart `inventory_health`.
-- This is not a local view/table definition in this repo.
-- It documents the upstream Fabric Lakehouse object used by downstream views/registry lineage.
