-- Source: SupplyChain_Warehouse.silver.vw_slv_invoice_detail_line_level
-- Generated from INFORMATION_SCHEMA.COLUMNS.
-- This is a logical schema snapshot; review Fabric physical options before execution.
CREATE TABLE [silver].[vw_slv_invoice_detail_line_level] (
    [id_invoice] varchar(200) NULL,
    [id_invoice_extended] varchar(8000) NULL,
    [id_order] varchar(8000) NULL,
    [num_item_sequence] int NULL,
    [id_customer] varchar(8000) NULL,
    [code_ship_to] varchar(8000) NULL,
    [id_account_ship_to] varchar(8000) NULL,
    [id_item_sku] varchar(8000) NULL,
    [code_warehouse] varchar(8000) NULL,
    [code_customer_group] varchar(8000) NULL,
    [num_lead_time_days] int NULL,
    [qty_shipped] decimal(12,3) NULL,
    [qty_ordered] decimal(12,3) NULL,
    [qty_backordered] decimal(12,3) NULL,
    [amt_invoice] decimal(14,2) NULL,
    [amt_net_sales] decimal(14,3) NULL,
    [amt_price] decimal(14,2) NULL,
    [amt_standard_price] decimal(14,2) NULL,
    [amt_contract_price] decimal(14,2) NULL,
    [amt_discount] decimal(12,2) NULL,
    [amt_price_adjustment] decimal(12,2) NULL,
    [amt_freight] decimal(12,2) NULL,
    [dt_invoice] date NULL,
    [dt_order] date NULL,
    [dt_request] date NULL,
    [dt_current_request] date NULL,
    [dt_current_promise] date NULL,
    [dt_original_request] date NULL,
    [dt_original_promise] date NULL,
    [dt_promised_delivery] date NULL,
    [dt_delivery] date NULL,
    [dt_actual_delivery] date NULL,
    [code_order_type] varchar(8000) NULL,
    [code_order_type_3] varchar(8000) NULL,
    [code_credit] varchar(8000) NULL,
    [code_item_class] varchar(8000) NULL,
    [code_order_item_status] varchar(8000) NULL
);
