-- Generated from live Fabric metadata: SupplyChain_Processing_Warehouse
CREATE TABLE [InventoryHistory_Enh].[HoldingTransferSnapshotDaily] (
    [SnapshotDate] date NULL,
    [TransferNumber] varchar(50) NULL,
    [TransferLine] int NULL,
    [ItemSku] varchar(50) NULL,
    [WarehouseCode] varchar(50) NULL,
    [SourceWarehouseCode] varchar(50) NULL,
    [ReceivingWarehouseCode] varchar(50) NULL,
    [ShipDateKey] int NULL,
    [ShipDate] date NULL,
    [ShipWeekEndingDate] date NULL,
    [DueDateKey] int NULL,
    [DueDate] date NULL,
    [DueWeekEndingDate] date NULL,
    [HeaderComment] varchar(200) NULL,
    [DetailComment] varchar(200) NULL,
    [TransferQty] decimal(18,4) NULL,
    [ShippedQty] decimal(18,4) NULL,
    [TotalShippedQty] decimal(18,4) NULL,
    [ExpediteCode] varchar(20) NULL,
    [FirmCode] varchar(20) NULL,
    [TransferCube] decimal(18,4) NULL,
    [HeaderStatus] varchar(10) NULL,
    [CancelFlag] varchar(10) NULL,
    [SourceSystem] varchar(64) NULL,
    [SourceTable] varchar(128) NULL,
    [LoadDT] datetime2(6) NULL
);
