-- Generated from live Fabric metadata: SupplyChain_Processing_Warehouse
CREATE TABLE [InventoryHistory_Enh].[InventorySnapshotWeekly] (
    [ItemSku] varchar(50) NULL,
    [WarehouseCode] varchar(50) NULL,
    [SnapshotDate] date NULL,
    [SnapshotWeekEndingDate] date NULL,
    [FiscalMonth] int NULL,
    [FiscalMonthDate] date NULL,
    [OnHandQty] decimal(18,4) NULL,
    [SafetyStockTarget] decimal(18,4) NULL,
    [IOSafetyStock] decimal(18,4) NULL,
    [OrderQty] decimal(18,4) NULL,
    [BuildQty] decimal(18,4) NULL,
    [MakeBuyCode] varchar(10) NULL,
    [SourceWarehouseCode] varchar(50) NULL,
    [PrimaryVendorNumber] varchar(50) NULL,
    [PrimaryVendorName] varchar(200) NULL,
    [PrimaryVendorSplit] varchar(50) NULL,
    [SecondaryVendorNumber] varchar(50) NULL,
    [SecondaryVendorName] varchar(200) NULL,
    [SecondaryVendorSplit] varchar(50) NULL,
    [ReplenishmentLeadTime] decimal(18,4) NULL,
    [SourceLabel] varchar(50) NULL,
    [SourceSystem] varchar(64) NULL,
    [SourceTable] varchar(128) NULL,
    [IsHistoricalWeeklySnapshot] int NULL,
    [IsLatestInventorySnapshot] int NULL,
    [SnapshotType] varchar(30) NULL,
    [LatestInventorySnapshotDate] date NULL,
    [LoadDT] datetime2(6) NULL
);
