-- Generated from live Fabric metadata: SupplyChain_Processing_Warehouse
CREATE TABLE [InventoryHistory_Enh].[SupplyPlanDetail] (
    [ItemSku] varchar(8000) NULL,
    [WarehouseCode] varchar(8000) NULL,
    [SnapshotDate] date NULL,
    [WeekEnding] date NULL,
    [BeginningBalanceQty] decimal(18,4) NULL,
    [FirmDemandQty] decimal(18,4) NULL,
    [NetFcstQty] decimal(18,4) NULL,
    [FirmTransferOutQty] decimal(18,4) NULL,
    [FirmProductionQty] decimal(18,4) NULL,
    [FirmPurchaseOrderQty] decimal(18,4) NULL,
    [InTransitTransferInQty] decimal(18,4) NULL,
    [OnOrderTransferInQty] decimal(18,4) NULL,
    [PlannedTransferInQty] decimal(18,4) NULL,
    [PlannedTransferOutQty] decimal(18,4) NULL,
    [PlannedProductionQty] decimal(18,4) NULL,
    [PlannedPurchaseOrderQty] decimal(18,4) NULL,
    [TotalReceiptQty] decimal(18,4) NULL,
    [SIQty] decimal(18,4) NULL,
    [SafetyStockQty] decimal(18,4) NULL,
    [MonthsOfSupplyQty] decimal(18,4) NULL,
    [ResultantForecastQty] decimal(18,4) NULL,
    [PromotionalLiftQty] decimal(18,4) NULL,
    [DemandFulfillmentQty] decimal(18,4) NULL,
    [WeeklyPromotionalLiftQty] decimal(18,4) NULL,
    [IsHistoricalWeeklySnapshot] int NULL,
    [IsLatestSupplyPlanSnapshot] int NULL,
    [SnapshotType] varchar(30) NULL,
    [LatestSupplyPlanSnapshotDate] date NULL,
    [SINegQty] decimal(18,4) NULL,
    [FirmDemandQtyNext7D] decimal(18,4) NULL,
    [IsActiveItemWhIn7DNext] int NOT NULL,
    [FirmDemandQtyNext14D] decimal(18,4) NULL,
    [NetFcstQtyNext14D] decimal(18,4) NULL,
    [IsActiveItemWhIn14DNext] int NOT NULL,
    [NetFcstQtyAtRisk] decimal(18,4) NULL,
    [FirmDemandQtyAtRisk] decimal(18,4) NULL,
    [LoadDT] datetime2(6) NULL
);
