Received: from SN4PR01MB994808.prod.exchangelabs.com (2603:10b6:806:502::14)
 by SN6PR01MB4000.prod.exchangelabs.com with HTTPS; Mon, 22 Jun 2026 16:43:40
 +0000
Received: from MW6PR01MB8318.prod.exchangelabs.com (2603:10b6:303:23c::12) by
 SN4PR01MB994808.prod.exchangelabs.com (2603:10b6:806:502::14) with Microsoft
 SMTP Server (version=TLS1_2, cipher=TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384) id
 15.21.113.18; Mon, 22 Jun 2026 16:43:39 +0000
Received: from MW6PR01MB8318.prod.exchangelabs.com
 ([fe80::1904:9626:e25f:4464]) by MW6PR01MB8318.prod.exchangelabs.com
 ([fe80::1904:9626:e25f:4464%6]) with mapi id 15.21.0139.018; Mon, 22 Jun 2026
 16:43:39 +0000
From: Datawarehouse Alerts <DatawarehouseAlerts@Ashleyfurniture.com>
To: "Steinke, Rick" <RSteinke@Ashleyfurniture.com>, Data Warehouse
	<DL_AFI_Analytics_AG_DataWarehouse@Ashleyfurniture.com>
Subject: EnterpriseData - ETL_Framework DataWarehouse Data Feed Alert: 0.2857%
 behind (1 of 350)
Thread-Topic: EnterpriseData - ETL_Framework DataWarehouse Data Feed Alert:
 0.2857% behind (1 of 350)
Thread-Index: AQHdAmZH0HB/fQgkWUyNu83XnzdLMg==
X-MS-Exchange-MessageSentRepresentingType: 1
Date: Mon, 22 Jun 2026 16:43:39 +0000
Message-ID:
	<MW6PR01MB83186DA3364C9342BF49DC1FA7EF2@MW6PR01MB8318.prod.exchangelabs.com>
Accept-Language: en-US
Content-Language: en-US
X-MS-Exchange-Organization-AuthAs: Internal
X-MS-Exchange-Organization-AuthMechanism: 04
X-MS-Exchange-Organization-AuthSource: MW6PR01MB8318.prod.exchangelabs.com
X-MS-Exchange-Organization-SupervisoryReview-OcrResultLocation:
	{"Status":"OcrRequired","CorrelationId":null,"Locations":null}
X-MS-Has-Attach:
X-Auto-Response-Suppress: DR, OOF, AutoReply
X-MS-Exchange-Organization-Network-Message-Id:
	32a0af57-3dea-4977-f541-08ded07d69b6
X-MS-Exchange-Organization-SCL: 1
X-MS-TNEF-Correlator:
X-MS-Exchange-Organization-RecordReviewCfmType: 0
x-ms-publictraffictype: Email
x-ms-exchange-crosstenant-id: 5a9d9cfd-c32e-4ac1-a9ed-fe83df4f9e4d
X-Microsoft-Antispam-Mailbox-Delivery:
	ucf:1;jmr:0;auth:0;dest:C;OFR:CustomRules;ENG:(910005)(920097)(425001)(930201)(20251009189)(140003)(1420198);
X-Microsoft-Antispam-Message-Info:
	l0cUwyOPeBQx2TxLCZxf1ZNpzDDc1iW6csmMhbHNLgAaHLSCBZsd0mySDQjdgJwpYnykAehNGcdYmXfaRtzTHkpNjwehXejHYr3WIwIndyChMYnqXDya0KgVrJ7Zf+mQ6ornR7To1OgesBWo4Kw/fBR34yQaHKEyvZArTuHrVlYlAiHGHN9BSpT/TsV2AJ4/CYmOzn6mWoojiDa5hIU9pTF99EADVUIaBuQDgMPy/Gwr+/CIiVmOGnxKImJcDBJK5ixK5veT8bkchvptaTT6SUfZXwnr2KMaVe7DTV+6wWskO1aQpkmuu4iYiui6H7NiNbTNc7skkuiQVdSvddNu4vKQXd5GQt+7h+5vjU3K7BasvYAGIDs0Uk57v/wl2jvEKRKWh36rIW3hruHlw411hsVJQkNm/OAUVk6kMoloJEXvcUG3bqXCGk+cP0ueclkS8cyu+2zuQiaTZXtKTPgNsYFD4cUikzJH7dE7nV2KeD4P2KXL5mxo1Ll/gm4uQgaH0z0X1BcZTKFgyVOSKGF3rRCTl8BR5+0usopsIn7ypXfarm8Hdp5eH41DjNPfecrC8/Dz4G9ZvY7+FdGxmdLsBOlKQqVGsge9Z969kZUM0APBl6LcepleaKCk2vWjIXg6b66+arT0XCDrnrbw70jM4zfvXeZFYztBMPbYjULfJJR+ueZOk+cRBKADaG1ZR36GEzwRuIKY5roPuRmq/NvF+jpqgBbFWsXQzPBoAwTW8LQ6ZMx3N5QbKmm3UrhDLW5ZUwkmZJxUVS6E+eaYuOpd67brIiis/X0pFB/FBmL6TQzf941RQcF4X0dqKXnbEgNnpFsCUMBAziglD/ovYx1LPrhDv8hzbTwLHjBdwb2VEHBiQ5BomnfiWNcrpGxrrxwB
Content-Type: multipart/alternative;
	boundary="_000_MW6PR01MB83186DA3364C9342BF49DC1FA7EF2MW6PR01MB8318prod_"
MIME-Version: 1.0

--_000_MW6PR01MB83186DA3364C9342BF49DC1FA7EF2MW6PR01MB8318prod_
Content-Type: text/plain; charset="us-ascii"

FABRIC Table Dictionary Objects that are behind schedule

As of: 2026-06-22 16:43:16

Behind: 1 of 350 (0.2857%)

Hours Late      Last Updated (UTC)      Refresh Rate (hours)    Schema Name     Table Name      Job Server      Job Name
50      2026-06-20 06:00:38     3       MasterData_ItemMaster_AFI       ITBEXT  Dwsaazp-radap01 Windows Task Scheduler-ItemMaster_Journal_Sync

--_000_MW6PR01MB83186DA3364C9342BF49DC1FA7EF2MW6PR01MB8318prod_
Content-Type: text/html; charset="us-ascii"

<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=us-ascii">
</head>
<body>
<h2>FABRIC Table Dictionary Objects that are behind schedule</h2>
<p><b>As of:</b> 2026-06-22 16:43:16</p>
<p><b>Behind:</b> 1 of 350 (0.2857%)</p>
<table border="1" cellspacing="0" cellpadding="4">
<thead>
<tr style="font-weight:bold;">
<td>Hours Late</td>
<td>Last Updated (UTC)</td>
<td>Refresh Rate (hours)</td>
<td>Schema Name</td>
<td>Table Name</td>
<td>Job Server</td>
<td>Job Name</td>
</tr>
</thead>
<tbody>
<tr>
<td>50</td>
<td>2026-06-20 06:00:38</td>
<td>3</td>
<td>MasterData_ItemMaster_AFI</td>
<td>ITBEXT</td>
<td>Dwsaazp-radap01</td>
<td>Windows Task Scheduler-ItemMaster_Journal_Sync</td>
</tr>
</tbody>
</table>
</body>
</html>

--_000_MW6PR01MB83186DA3364C9342BF49DC1FA7EF2MW6PR01MB8318prod_--
