-- Physical final table contract: [SupplyChain_Processing_Warehouse].[SalesHistory_Enh].[ActualDemandWeekly]
-- Loaded by ETL_Framework from [SupplyChain_Processing_Warehouse].[SalesHistory_Enh_Wrk].[v_ActualDemandWeekly].
-- Business/source view SQL is documented in ../SalesHistory_Enh_Wrk/v_ActualDemandWeekly.sql.
